In [1]:
import pickle

import pandas as pnd

import cobra
import gempipe

from memote.support.consistency import find_unconserved_metabolites

# define useful functions

In [2]:
from helper_functions import *

# 01_klebsiella

In [3]:
# load reference model
iYL1228 = cobra.io.read_sbml_model('01_klebsiella/reference/iYL1228.xml')
gempipe.sanity_report(iYL1228)

gempipe v1.38.1 - sanity_report
model ID: iYL1228
G: 1229 R: 2262 M: 1658 uM: 1055 groups: 0
Compartments: ['c', 'e', 'p']
Biomass assemblies: 1 ['BIOMASS_']
Objectives: 1 ['BIOMASS_']
Optimization: 1.0426374979773743 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 0
Sinks/demands: 2
Constrained metabolic: 15
With 'artificial' atoms: 0
Missing formulas - charges: 1658 - 0
Mass - charge unbalances: 0 - 0

## get proteomes

In [4]:
# get FASTA proteomes of modeled genes
# nucleotidic
_ = fasta_to_modeled(iYL1228, ['01_klebsiella/reference/CP000647.1.fna'], '01_klebsiella/reference/iYL1228.fna')
# amino aicdic
_ = fasta_to_modeled(iYL1228, ['01_klebsiella/reference/CP000647.1.faa'], '01_klebsiella/reference/iYL1228.faa')

Recovered 1228 / 1229.
Missing 1 : {'KPN_SPONT'}
Recovered 1228 / 1229.
Missing 1 : {'KPN_SPONT'}

## remove strain-specific biom precursors

In [5]:
# delete strain specific components from biomass: udpgalur_c , udpgal_c, dtdprmn_c

r_string = iYL1228.reactions.BIOMASS_.reaction
r_string = r_string.replace(' + 0.076 udpgal_c', '')
r_string = r_string.replace(' + 0.001 udpgalur_c', '')
r_string = r_string.replace(' + 0.142 dtdprmn_c', '')
iYL1228.reactions.BIOMASS_.build_reaction_from_string(r_string)

gempipe.sanity_report(iYL1228)

gempipe v1.38.1 - sanity_report
model ID: iYL1228
G: 1229 R: 2262 M: 1658 uM: 1055 groups: 0
Compartments: ['c', 'e', 'p']
Biomass assemblies: 1 ['BIOMASS_']
Objectives: 1 ['BIOMASS_']
Optimization: 1.084689665727891 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 0
Sinks/demands: 2
Constrained metabolic: 15
With 'artificial' atoms: 0
Missing formulas - charges: 1658 - 0
Mass - charge unbalances: 0 - 0

## relax diffusions

In [6]:
# relax diffusions / facilitate diffusion / flipping involved in Biolog assays

biolog_mappings = gempipe.get_biolog_mappings()
biolog_pure_mids = set(biolog_mappings[biolog_mappings['BiGG_exchange'].notna()]['BiGG_exchange'].to_list())
biolog_pure_mids = set([i.replace('EX_', '').rsplit('_', 1)[0] for i in biolog_pure_mids])

for r in iYL1228.reactions:
    
    # if it's involved in Biolog substrates:
    if any([i in biolog_pure_mids for i in [m.id.rsplit('_', 1)[0] for m in r.metabolites]]):
    
        # diffusions / facilitate diffusion / flipping:
        if len(r.metabolites)==2 and len(set([r.id.rsplit('_', 1)[-1] for r in r.metabolites]))==2:
            if r.bounds != (-1000, 1000):
                
                print(r.id, r.reaction, r.name, r.bounds)
                r.bounds = (-1000, 1000)

ACMANAtex acmana_e <-- acmana_p N-acetyl-D-mannosamine transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
ABUTtex 4abut_e <-- 4abut_p 4-aminobutyrate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
AKGtex akg_e <-- akg_p Alpha-ketoglutarate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
CYStpp cys__L_c --> cys__L_p L-cysteine export via facilitated transport (0.0, 1000.0)
DCAtex dca_e <-- dca_p Decanoate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
FUMtex fum_e <-- fum_p Fumarate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
GLCtex_copy2 glc__D_e --> glc__D_p Glucose transport via diffusion (extracellular to periplasm) (0.0, 1000.0)
HXAtex hxa_e <-- hxa_p Hexanoate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
FORtex for_e <-- for_p Formate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
FORtppi for_c --> for_p Formate transport via diffusion (cytoplasm to periplasm) (0.0, 1000.0)
MALTTRtexi malttr_e --> malttr_p Maltotriose transport via diffusion (extracellular to periplasm) irreversible (0.0, 1000.0)
MALTtexi malt_e --> malt_p MaltoseMaltotriose transport via diffusion (extracellular to periplasm) irreversible (0.0, 1000.0)
MALDtex mal__D_e <-- mal__D_p D-Malate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
NO2tex no2_e <-- no2_p Nitrite transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
NO3tex no3_e <-- no3_p Nitrate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
PEAMNtex peamn_e <-- peamn_p Phenethylamine transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
SUCCtex succ_e <-- succ_p Succinate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
THRtex thr__L_e <-- thr__L_p L-threonine transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)
TARTRtex tartr__L_e <-- tartr__L_p Tartrate transport via diffusion (extracellular to periplasm) (-1000.0, 0.0)

## save medium recipe

In [7]:
# set the main growth medium
apply_medium(iYL1228)
iYL1228.slim_optimize()

1.0630380418232899

In [8]:
# save the recipe for gap-filling
# for gempipe
save_recipe(iYL1228, flavour='gempipe', medium_id='medium_gempipe', outpath='01_klebsiella/reference/')
# for carveme
save_recipe(iYL1228, flavour='carveme', medium_id='medium_carveme', outpath='01_klebsiella/reference/')
# for bactabolize
save_recipe(iYL1228, flavour='bactabolize', medium_id='medium_bactabolize', outpath='01_klebsiella/reference/')

## check ATPM

In [9]:
# check the maintenance:
iYL1228.reactions.get_by_id('ATPM')

## save edited version

In [10]:
# save reference:
cobra.io.write_sbml_model(iYL1228, '01_klebsiella/reference/iYL1228_edited.xml')

# 02_ralstonia

In [11]:
%%capture --no-stdout

# load reference model
# cobrapy-compatible version obtained from carveme's suppl.mat.
iRP1476 = cobra.io.read_sbml_model('02_ralstonia/reference/iRP1476.xml')
gempipe.sanity_report(iRP1476)

gempipe v1.38.1 - sanity_report
model ID: iRP1476
G: 2600 R: 2644 M: 2121 uM: 1420 groups: 253
Compartments: ['c', 'e', 'p']
Biomass assemblies: 1 ['BIOMASS']
Objectives: 1 ['BIOMASS']
Optimization: 96.36243618282448 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 2
Sinks/demands: 16
Constrained metabolic: 0
With 'artificial' atoms: 0
Missing formulas - charges: 2121 - 2121
Mass - charge unbalances: 0 - 0

## restore stoichiometric consistency

In [12]:
# launch the memote function: 

un_mids = [m.id for m in find_unconserved_metabolites(iRP1476)]
print(un_mids)

['ampi_p', 'cafe_e', 'cana__L_c', 'cd2_c', 'cana__L_e', 'tom_e', 'esclt_p', 'cd2_e', 'mincyc_p', 'mincyc_e', 'ni2_c', 'ni2_e', 'rfamp_p', 'ni2_p', 'hg2_c', 'cro4_p', 'hg2_e', 'rfamp_e', 'cana__L_p', 'doxrbcn_p', 'resoc_p', 'berb_p', 'cafe_p', 'naldx_e', 'ag_c', 'ag_e', 'fusar_e', 'hg2_p', 'cro4_e', 'naldx_p', 'doxrbcn_e', 'cro4_c', 'fusar_p', 'resoc_e', 'fusa_e', 'ttrcyc_p', 'cm_p', 'acfv_p', 'zn2_p', 'ttrcyc_e', 'ampi_e', 'novbcn_p', 'esclt_e', 'tom_p', 'zn2_c', 'cd2_p', 'cm_e', 'fusa_p', 'acfv_e', 'ag_p', 'zn2_e', 'novbcn_e', 'berb_e']

In [13]:
print(iRP1476.reactions.Naldxteff.reaction)
print(iRP1476.reactions.CD2teff_e.reaction)
print(iRP1476.reactions.NI2t3pp.reaction)
print(iRP1476.reactions.CD2t3pp.reaction)
print(iRP1476.reactions.AGt3pp.reaction)
print(iRP1476.reactions.CMtpp.reaction)
print(iRP1476.reactions.Escltteff.reaction)
print(iRP1476.reactions.cafeteff.reaction)
print(iRP1476.reactions.RFAMPtpp.reaction)
print(iRP1476.reactions.MINCYCtpp.reaction)
print(iRP1476.reactions.Resocteff.reaction)
print(iRP1476.reactions.ZN2teff_e.reaction)
print(iRP1476.reactions.CRO4t3pp.reaction)
print(iRP1476.reactions.DOXRBCNtpp.reaction)
print(iRP1476.reactions.FUSAtpp.reaction)
print(iRP1476.reactions.acfvteff.reaction)
print(iRP1476.reactions.ampiteff.reaction)
print(iRP1476.reactions.NOVBCNtpp.reaction)
print(iRP1476.reactions.TTRCYCtpp.reaction)
print(iRP1476.reactions.ZN2t3pp.reaction)
print(iRP1476.reactions.Berbteff.reaction)
print(iRP1476.reactions.Tomteff.reaction)
print(iRP1476.reactions.Fusarteff.reaction)
print(iRP1476.reactions.CANAt2pp.reaction)
print(iRP1476.reactions.HG2t3pp.reaction)

print(iRP1476.reactions.HG2abcpp.reaction)
print(iRP1476.reactions.ZN2abcpp.reaction)
print(iRP1476.reactions.CD2abcpp.reaction)
print(iRP1476.reactions.NI2abcpp.reaction)

print(iRP1476.reactions.CD2t4pp.reaction)
print(iRP1476.reactions.ZN2t4pp.reaction)

h_p + naldx_p --> h_c
cd2_p + h_p --> h_c
h_p + ni2_c --> h_c
cd2_c + h_p --> h_c
ag_c + h_p --> h_c
cm_p + h_p --> h_c
esclt_p + h_p --> h_c
cafe_p + h_p --> h_c
h_p + rfamp_p --> h_c
h_p + mincyc_p --> h_c
h_p + resoc_p --> h_c
h_p + zn2_p --> h_c
cro4_c + h_p --> h_c
doxrbcn_p + h_p --> h_c
fusa_p + h_p --> h_c
acfv_p + h_p --> h_c
ampi_p + h_p --> h_c
h_p + novbcn_p --> h_c
h_p + ttrcyc_p --> h_c
h_p + zn2_c --> h_c
berb_p + h_p --> h_c
h_p + tom_p --> h_c
fusar_p + h_p --> h_c
cana__L_c + h_p --> h_c
h_p + hg2_c --> h_c
atp_c + h2o_c + hg2_c --> adp_c + h_c + pi_c
atp_c + h2o_c + zn2_c --> adp_c + h_c + pi_c
atp_c + cd2_c + h2o_c --> adp_c + h_c + pi_c
atp_c + h2o_c + ni2_c --> adp_c + h_c + pi_c
cd2_c + h_p + k_p --> h_c + k_c
h_p + k_p + zn2_c --> h_c + k_c

In [14]:
iRP1476.reactions.Naldxteff.build_reaction_from_string('h_p + naldx_p --> h_c + naldx_c')
iRP1476.reactions.CD2teff_e.build_reaction_from_string('cd2_p + h_p --> h_c + cd2_c')
iRP1476.reactions.NI2t3pp.build_reaction_from_string('h_p + ni2_c --> h_c + ni2_p')
iRP1476.reactions.CD2t3pp.build_reaction_from_string('cd2_c + h_p --> h_c + cd2_p')
iRP1476.reactions.AGt3pp.build_reaction_from_string('ag_c + h_p --> h_c + ag_p')
iRP1476.reactions.CMtpp.build_reaction_from_string('cm_p + h_p --> h_c + cm_c')
iRP1476.reactions.Escltteff.build_reaction_from_string('esclt_p + h_p --> h_c + esclt_c')
iRP1476.reactions.cafeteff.build_reaction_from_string('cafe_p + h_p --> h_c + cafe_c')
iRP1476.reactions.RFAMPtpp.build_reaction_from_string('h_p + rfamp_p --> h_c + rfamp_c')
iRP1476.reactions.MINCYCtpp.build_reaction_from_string('h_p + mincyc_p --> h_c + mincyc_c')
iRP1476.reactions.Resocteff.build_reaction_from_string('h_p + resoc_p --> h_c + resoc_c')
iRP1476.reactions.ZN2teff_e.build_reaction_from_string('h_p + zn2_p --> h_c + zn2_c')
iRP1476.reactions.CRO4t3pp.build_reaction_from_string('cro4_c + h_p --> h_c + cro4_p')
iRP1476.reactions.DOXRBCNtpp.build_reaction_from_string('doxrbcn_p + h_p --> h_c + doxrbcn_c')
iRP1476.reactions.FUSAtpp.build_reaction_from_string('fusa_p + h_p --> h_c + fusa_c')
iRP1476.reactions.acfvteff.build_reaction_from_string('acfv_p + h_p --> h_c + acfv_c')
iRP1476.reactions.ampiteff.build_reaction_from_string('ampi_p + h_p --> h_c + ampi_c')
iRP1476.reactions.NOVBCNtpp.build_reaction_from_string('h_p + novbcn_p --> h_c + novbcn_c')
iRP1476.reactions.TTRCYCtpp.build_reaction_from_string('h_p + ttrcyc_p --> h_c + ttrcyc_c')
iRP1476.reactions.ZN2t3pp.build_reaction_from_string('h_p + zn2_c --> h_c + zn2_p')
iRP1476.reactions.Berbteff.build_reaction_from_string('berb_p + h_p --> h_c + berb_c')
iRP1476.reactions.Tomteff.build_reaction_from_string('h_p + tom_p --> h_c + tom_c')
iRP1476.reactions.Fusarteff.build_reaction_from_string('fusar_p + h_p --> h_c + fusar_c')
iRP1476.reactions.CANAt2pp.build_reaction_from_string('cana__L_c + h_p --> h_c + cana__L_p')
iRP1476.reactions.HG2t3pp.build_reaction_from_string('h_p + hg2_c --> h_c + hg2_p')

iRP1476.reactions.HG2abcpp.build_reaction_from_string('atp_c + h2o_c + hg2_c --> hg2_p + adp_c + h_c + pi_c')
iRP1476.reactions.ZN2abcpp.build_reaction_from_string('atp_c + h2o_c + zn2_c --> zn2_p + adp_c + h_c + pi_c')
iRP1476.reactions.CD2abcpp.build_reaction_from_string('atp_c + h2o_c + cd2_c --> cd2_p + adp_c + h_c + pi_c')
iRP1476.reactions.NI2abcpp.build_reaction_from_string('atp_c + h2o_c + ni2_c --> ni2_p + adp_c + h_c + pi_c')

iRP1476.reactions.CD2t4pp.build_reaction_from_string('cd2_c + h_p + k_p --> cd2_p + h_c + k_c')
iRP1476.reactions.ZN2t4pp.build_reaction_from_string('zn2_c + h_p + k_p --> zn2_p + h_c + k_c')

unknown metabolite 'naldx_c' created
unknown metabolite 'cm_c' created
unknown metabolite 'esclt_c' created
unknown metabolite 'cafe_c' created
unknown metabolite 'rfamp_c' created
unknown metabolite 'mincyc_c' created
unknown metabolite 'resoc_c' created
unknown metabolite 'doxrbcn_c' created
unknown metabolite 'fusa_c' created
unknown metabolite 'acfv_c' created
unknown metabolite 'ampi_c' created
unknown metabolite 'novbcn_c' created
unknown metabolite 'ttrcyc_c' created
unknown metabolite 'berb_c' created
unknown metabolite 'tom_c' created
unknown metabolite 'fusar_c' created

In [15]:
iRP1476.metabolites.naldx_c.compartment = 'c'
iRP1476.metabolites.cm_c.compartment = 'c'
iRP1476.metabolites.esclt_c.compartment = 'c'
iRP1476.metabolites.cafe_c.compartment = 'c'
iRP1476.metabolites.rfamp_c.compartment = 'c'
iRP1476.metabolites.mincyc_c.compartment = 'c'
iRP1476.metabolites.resoc_c.compartment = 'c'
iRP1476.metabolites.doxrbcn_c.compartment = 'c'
iRP1476.metabolites.fusa_c.compartment = 'c'
iRP1476.metabolites.acfv_c.compartment = 'c'
iRP1476.metabolites.ampi_c.compartment = 'c'
iRP1476.metabolites.novbcn_c.compartment = 'c'
iRP1476.metabolites.ttrcyc_c.compartment = 'c'
iRP1476.metabolites.berb_c.compartment = 'c'
iRP1476.metabolites.tom_c.compartment = 'c'
iRP1476.metabolites.fusar_c.compartment = 'c'

In [16]:
# launch the memote function (again)
# check if the stoichiometric consistency is restored:

un_mids = [m.id for m in find_unconserved_metabolites(iRP1476)]
print(un_mids)

[]

## correct GPRs

In [17]:
# correct gprs: 

ARBTNLSYN = iRP1476.reactions.ARBTNLSYN
ARBTNLSYN.gene_reaction_rule = "RSp0419 and RSp0421 and RSp0422"  # correct RSp042 to RSp0421.
ARBTNLSYN.update_genes_from_gpr()

## remove anti-convention genes

In [18]:
# rename genes, adjust gprs:
for r in iRP1476.reactions:
    gpr = r.gene_reaction_rule
    
    # each gene must be surrounded by spaces:
    gpr = ' ' + gpr.replace('(', '( ').replace(')', ') ') + ' '
    for g in r.genes: 
        if g.id.startswith('G_'): gpr = gpr.replace(f' {g.id} ', f' {g.id[2:]} ')
        if g.id.startswith('e'):  gpr = gpr.replace(f' {g.id} ', f'  ')              # exchanges
        if g.id.startswith('d'):  gpr = gpr.replace(f' {g.id} ', f' spontaneous ')   # diffusions
        if g.id.startswith('s'):  gpr = gpr.replace(f' {g.id} ', f' spontaneous ')   # spontaneous
        if g.id == 'NoAssignment':  gpr = gpr.replace(f' {g.id} ', f'  ')
    gpr = gpr.replace('(', '( ').replace(')', ') ')[1:-1]
    r.gene_reaction_rule = gpr
    r.update_genes_from_gpr()
    
    
# remove genes remained without associated reactions: 
to_remove = []
for g in iRP1476.genes:
    if len(g.reactions) == 0:
        to_remove.append(g)
cobra.manipulation.remove_genes(iRP1476, to_remove, remove_reactions=False)

## remove strain-specific biom precursors

In [19]:
# spmd_c Spermidine
# adocbl_c Adenosylcobalamin

BIOMASS = iRP1476.reactions.BIOMASS
ba = BIOMASS.reaction
ba = ba.replace(' + 0.006744 spmd_c', '')
ba = ba.replace(' + 0.000223 adocbl_c', '')
iRP1476.reactions.BIOMASS.build_reaction_from_string(ba)

gempipe.sanity_report(iRP1476)

gempipe v1.38.1 - sanity_report
model ID: iRP1476
G: 1477 R: 2644 M: 2137 uM: 1420 groups: 253
Compartments: ['c', 'e', 'p']
Biomass assemblies: 1 ['BIOMASS']
Objectives: 1 ['BIOMASS']
Optimization: 96.373688558369 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 2
Sinks/demands: 16
Constrained metabolic: 0
With 'artificial' atoms: 0
Missing formulas - charges: 2137 - 2137
Mass - charge unbalances: 0 - 0

## add Ca2+ uptake

In [20]:
uni = gempipe.get_universe('neg')

gempipe.import_from_universe(iRP1476, uni, 'EX_ca2_e')
gempipe.import_from_universe(iRP1476, uni, 'CAt4')

# now formula/charges for Ca2+ have been added
# but the reference doesn't use formula/charges:

iRP1476.metabolites.ca2_e.formula = None
iRP1476.metabolites.ca2_e.charge = None

iRP1476.metabolites.ca2_c.formula = None
iRP1476.metabolites.ca2_c.charge = None

## save medium recipe

In [21]:
apply_medium(iRP1476)
iRP1476.reactions.get_by_id('EX_glc__D_e').lower_bound = 0
iRP1476.reactions.get_by_id('EX_gln__L_e').lower_bound = -10
iRP1476.slim_optimize()

0.999991187577652

In [22]:
# save the recipe for gap-filling
# for gempipe
save_recipe(iRP1476, flavour='gempipe', medium_id='medium_gempipe', outpath='02_ralstonia/reference/')
# for carveme
save_recipe(iRP1476, flavour='carveme', medium_id='medium_carveme', outpath='02_ralstonia/reference/')
# for bactabolize
save_recipe(iRP1476, flavour='bactabolize', medium_id='medium_bactabolize', outpath='02_ralstonia/reference/')

## get proteomes

In [23]:
# get FASTA proteomes of modeled genes
# nucleotidic
added = fasta_to_modeled(iRP1476, ['02_ralstonia/reference/AL646052.1.fna', '02_ralstonia/reference/AL646053.1.fna'], '02_ralstonia/reference/iRP1476.fna')
# amino aicdic
added = fasta_to_modeled(iRP1476, ['02_ralstonia/reference/AL646052.1.faa', '02_ralstonia/reference/AL646053.1.faa'], '02_ralstonia/reference/iRP1476.faa')

Recovered 1427 / 1476.
Missing 49 : {'RS04531', 'RS04004', 'RS05733', 'RS04532', 'RS03325', 'RS03939', 'RS04003', 'RS03938', 'RS04829', 'RALSOc_3512', 'RS05586', 'RS02887', 'RS05585', 'RS05732', 'RS03940', 'RS04528', 'RS04002', 'RS03726', 'RS04005', 'RS05382', 'RS00235', 'RS04530', 'RS05584', 'RS03462', 'RS02241', 'RS01509', 'RS02877', 'RS05583', 'RS05381', 'RS02886', 'RS04001', 'RS01505', 'RS04529', 'RS00484', 'RS04383', 'RS03760', 'RSc3445', 'RS03461', 'RS01507', 'RS00330', 'RS01162', 'RS02662', 'RS02400', 'RS03937', 'RS04716', 'RS03460', 'RS00236', 'RS05795', 'RS04914'}
Recovered 1427 / 1476.
Missing 49 : {'RS04531', 'RS04004', 'RS05733', 'RS04532', 'RS03325', 'RS03939', 'RS04003', 'RS03938', 'RS04829', 'RALSOc_3512', 'RS05586', 'RS02887', 'RS05585', 'RS05732', 'RS03940', 'RS04528', 'RS04002', 'RS03726', 'RS04005', 'RS05382', 'RS00235', 'RS04530', 'RS05584', 'RS03462', 'RS02241', 'RS01509', 'RS02877', 'RS05583', 'RS05381', 'RS02886', 'RS04001', 'RS01505', 'RS04529', 'RS00484', 'RS04383', 'RS03760', 'RSc3445', 'RS03461', 'RS01507', 'RS00330', 'RS01162', 'RS02662', 'RS02400', 'RS03937', 'RS04716', 'RS03460', 'RS00236', 'RS05795', 'RS04914'}

In [24]:
# parsing GenBanks more sequences are recovered:
gb_files = ['02_ralstonia/reference/AL646052.1.gb', '02_ralstonia/reference/AL646053.1.gb', '02_ralstonia/reference/NC_003295.1.gb', '02_ralstonia/reference/NC_003296.1.gb']
# nucleotidic
added = gb_to_modeled(iRP1476, gb_files, '02_ralstonia/reference/iRP1476.fna')
# amino aicdic
added = gb_to_modeled(iRP1476, gb_files, '02_ralstonia/reference/iRP1476.faa')

/opt/conda/lib/python3.9/site-packages/Bio/Seq.py:3482: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

Recovered 1474 / 1476.
Missing 2 : {'RSc3445', 'RALSOc_3512'}
Recovered 1474 / 1476.
Missing 2 : {'RSc3445', 'RALSOc_3512'}

## remove missing genes

In [25]:
# remove missing genes without removing reactions:

to_remove = [iRP1476.genes.get_by_id('RSc3445'), iRP1476.genes.get_by_id('RALSOc_3512')]
cobra.manipulation.remove_genes(iRP1476, to_remove, remove_reactions=False)

print(len(iRP1476.genes))

1475

## check ATPM

In [26]:
iRP1476.reactions.get_by_id('NGAME')

In [27]:
iRP1476.reactions.get_by_id('NGAME').bounds = (8.38, 8.38)

gempipe.sanity_report(iRP1476)

gempipe v1.38.1 - sanity_report
model ID: iRP1476
G: 1475 R: 2646 M: 2139 uM: 1421 groups: 253
Compartments: ['c', 'e', 'p']
Biomass assemblies: 1 ['BIOMASS']
Objectives: 1 ['BIOMASS']
Optimization: 0.999991187577652 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 2
Sinks/demands: 16
Constrained metabolic: 1
With 'artificial' atoms: 0
Missing formulas - charges: 2139 - 2139
Mass - charge unbalances: 0 - 0

## save edited version

In [28]:
# save reference:
cobra.io.write_sbml_model(iRP1476, '02_ralstonia/reference/iRP1476_edited.xml')

# 03_pseudomonas

In [29]:
# load reference model
iJN1463 = cobra.io.read_sbml_model('03_pseudomonas/reference/iJN1463.xml')
gempipe.sanity_report(iJN1463)

gempipe v1.38.1 - sanity_report
model ID: iJN1463
G: 1462 R: 2927 M: 2153 uM: 1432 groups: 0
Compartments: ['c', 'e', 'p']
Biomass assemblies: 2 ['BIOMASS_KT2440_Core2', 'BIOMASS_KT2440_WT3']
Objectives: 1 ['BIOMASS_KT2440_WT3']
Optimization: 0.5861175448479812 optimal (cplex)
Unconstrained LB-UB: (-999999.0, 999999.0)
Bad EX_change notation: 0
Sinks/demands: 33
Constrained metabolic: 2449
With 'artificial' atoms: 199
Missing formulas - charges: 0 - 0
Mass - charge unbalances: 4 - 3

## restore stoichiometric consistency

In [30]:
# launch the memote function: 

un_mids = [m.id for m in find_unconserved_metabolites(iJN1463)]
print(un_mids)

['h_p', 'h_e', 'h_c']

In [31]:
iJN1463.reactions.HDH.build_reaction_from_string(
    'h2o_c + histd_c + 2.0 nad_c --> 3.0 h_c + his__L_c + 2.0 nadh_c')
iJN1463.reactions.APPAT.build_reaction_from_string(
    'atp_c + h_c + pan4p_c --> dpcoa_c + ppi_c')
iJN1463.reactions.ARGDI.build_reaction_from_string(
    'arg__L_c + h2o_c --> citr__L_c + nh4_c')
iJN1463.reactions.PPRGL.build_reaction_from_string(
    'atp_c + gly_c + pram_c --> adp_c + gar_c + h_c + pi_c')
iJN1463.reactions.REPHACCOAT.build_reaction_from_string(
    'rephaccoa_c --> coa_c + rephac_c')
iJN1463.reactions.IDPh_1.build_reaction_from_string(
    'h2o_c + ppi_c --> 2.0 pi_c + h_c')
iJN1463.reactions.MEPCT_1.build_reaction_from_string(
    '2me4p_c + ctp_c + h_c --> 4c2me_c + ppi_c')


# FE3PYOVDDR fe3pyovd_p <=> fe2_p + pyovd_p (-999999.0, 999999.0)
# FE3PYOVDL fe3pyovd_e <=> fe3_e + pyovd_e  (-999999.0, 999999.0)
iJN1463.remove_reactions([iJN1463.reactions.FE3PYOVDDR, iJN1463.reactions.FE3PYOVDL])

# PQQAC pqqA_kt_c --> 2.0 h_c + pqqAc_kt_c (0.0, 999999.0)
# PQQFEP 4.0 h2o_c + pqqAc_kt_c --> 4pqq_c + tripeptide_c (0.0, 999999.0)
iJN1463.metabolites.tripeptide_c.formula = 'RHO'
iJN1463.reactions.PQQFEP.build_reaction_from_string(
    '5.0 h2o_c + pqqAc_kt_c --> 4pqq_c + tripeptide_c')

In [32]:
# launch the memote function (again)
# check if the stoichiometric consistency is restored:

un_mids = [m.id for m in find_unconserved_metabolites(iJN1463)]
print(un_mids)

[]

## remove strain-specific biomass precursors

In [33]:
# set the unconstrained lb/ub to -1000/1000:
gempipe.reset_unconstrained_bounds(iJN1463)

# select the core biomass assembly
iJN1463.reactions.BIOMASS_KT2440_WT3.bounds = (0,0 )
iJN1463.reactions.BIOMASS_KT2440_Core2.bounds = (0,1000 )
iJN1463.objective = 'BIOMASS_KT2440_Core2'

gempipe.sanity_report(iJN1463)

gempipe v1.38.1 - sanity_report
model ID: iJN1463
G: 1462 R: 2925 M: 2153 uM: 1432 groups: 0
Compartments: ['c', 'e', 'p']
Biomass assemblies: 2 ['BIOMASS_KT2440_Core2', 'BIOMASS_KT2440_WT3']
Objectives: 1 ['BIOMASS_KT2440_Core2']
Optimization: 0.5867762516977003 optimal (cplex)
Unconstrained LB-UB: (-1000, 1000)
Bad EX_change notation: 0
Sinks/demands: 33
Constrained metabolic: 5
With 'artificial' atoms: 199
Missing formulas - charges: 0 - 0
Mass - charge unbalances: 0 - 0

## save medium recipe

In [34]:
# set the main growth medium
apply_medium(iJN1463)
iJN1463.reactions.get_by_id('EX_na1_e').lower_bound = -1000   
iJN1463.reactions.get_by_id('EX_ni2_e').lower_bound = -1000   

iJN1463.slim_optimize()

0.980737772748016

In [35]:
# save the recipe for gap-filling
# for gempipe
save_recipe(iJN1463, flavour='gempipe', medium_id='medium_gempipe', outpath='03_pseudomonas/reference/')
# for carveme and gempipe-rf
with iJN1463:  # na1 are ni2 not in CarveMe's universal biomass
    iJN1463.reactions.get_by_id('EX_na1_e').lower_bound = 0   
    iJN1463.reactions.get_by_id('EX_ni2_e').lower_bound = 0 
    save_recipe(iJN1463, flavour='carveme', medium_id='medium_carveme', outpath='03_pseudomonas/reference/')
    save_recipe(iJN1463, flavour='gempipe', medium_id='medium_gempipe_rf', outpath='03_pseudomonas/reference/')
# for bactabolize
save_recipe(iJN1463, flavour='bactabolize', medium_id='medium_bactabolize', outpath='03_pseudomonas/reference/')

## get proteomes

In [36]:
# parsing GenBanks more sequences are recovered:
gb_files = ['03_pseudomonas/reference/NC_002947.4.gb']
# nucleotidic
added = gb_to_modeled(iJN1463, gb_files, '03_pseudomonas/reference/iJN1463.fna')
# amino aicdic
added = gb_to_modeled(iJN1463, gb_files, '03_pseudomonas/reference/iJN1463.faa')

Recovered 1441 / 1462.
Missing 21 : {'pWW0_131', 'PP_s0001', 'pWW0_092', 'pWW0_090', 'pWW0_130', 'pWW0_091', 'pWW0_095', 'PP_3462', 'pWW0_094', 'pWW0_101', 'pWW0_128', 'pWW0_096', 'PP_2519', 'pWW0_129', 'pWW0_127', 'pWW0_100', 'pWW0_097', 'pWW0_099', 'PP_3465', 'pWW0_093', 'pWW0_102'}
Recovered 1441 / 1462.
Missing 21 : {'pWW0_131', 'PP_s0001', 'pWW0_092', 'pWW0_090', 'pWW0_130', 'pWW0_091', 'pWW0_095', 'PP_3462', 'pWW0_094', 'pWW0_101', 'pWW0_128', 'pWW0_096', 'PP_2519', 'pWW0_129', 'pWW0_127', 'pWW0_100', 'pWW0_097', 'pWW0_099', 'PP_3465', 'pWW0_093', 'pWW0_102'}

## remove missing genes

In [37]:
# remove missing genes without removing the reaction: 
to_remove = (set([g.id for g in iJN1463.genes]) - set(['PP_s0001'])) - added 
to_remove = [iJN1463.genes.get_by_id(gid) for gid in to_remove]
cobra.manipulation.remove_genes(iJN1463, to_remove, remove_reactions=False)

print(len(iJN1463.genes))

1442

## check ATPM

In [38]:
iJN1463.reactions.get_by_id('ATPM')

## save edited version

In [39]:
# save reference:
cobra.io.write_sbml_model(iJN1463, '03_pseudomonas/reference/iJN1463_edited.xml')

# 04_streptococcus

In [3]:
Hirose2024 = cobra.io.load_json_model('04_streptococcus/reference/DataS1_iYH543.json')
gempipe.sanity_report(Hirose2024)

gempipe v1.38.2 - sanity_report
model ID: iYH543_20240105
G: 550 R: 1145 M: 970 uM: 820 groups: 0
Compartments: ['c', 'e']
Biomass assemblies: 1 ['EX_biomass_e']
Objectives: 1 ['bio1']
Optimization: 0.7540032375849974 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 0
Sinks/demands: 22
Constrained metabolic: 0
With 'artificial' atoms: 148
Missing formulas - charges: 1 - 970
Mass - charge unbalances: 11 - 0

## remove anti-convention genes

In [4]:
# Remove the 'Unknown' gene, respecting convention
for r in Hirose2024.reactions:
    gpr = r.gene_reaction_rule
    gpr = gpr.replace(f' and Unknown and ', f' and ')
    gpr = gpr.replace(f' or Unknown or ', f' or ')
    gpr = gpr.replace(f' and Unknown or ', f' or ')   
    gpr = gpr.replace(f' or Unknown and ', f' or ')   
    gpr = gpr.replace(f'Unknown or ', f'')   
    gpr = gpr.replace(f'Unknown and ', f'') 
    gpr = gpr.replace(f' or Unknown', f'')  
    gpr = gpr.replace(f' and Unknown', f'')  
    gpr = gpr.replace(f'Unknown', f'')   
    r.gene_reaction_rule = gpr
    r.update_genes_from_gpr()
    
    
# remove genes remained without associated reactions: 
to_remove = []
for g in Hirose2024.genes:
    if len(g.reactions) == 0:
        to_remove.append(g)
cobra.manipulation.remove_genes(Hirose2024, to_remove, remove_reactions=False)

## get proteomes

In [5]:
# nucleotidic
added = gb_to_modeled(Hirose2024, ['04_streptococcus/reference/AE004092.2.gb'], '04_streptococcus/reference/iYH543.fna')
# amino aicdic
added = gb_to_modeled(Hirose2024, ['04_streptococcus/reference/AE004092.2.gb'], '04_streptococcus/reference/iYH543.faa')

/opt/conda/lib/python3.9/site-packages/Bio/Seq.py:3482: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

Recovered 543 / 549.
Missing 6 : {'160490.1.1075.peg', '160490.1.1072_24.peg', '160490.1.1384_8.peg', '160490.1.1073_23.peg', '160490.1.1071_25.peg', '160490.1.1074_22.peg'}
Recovered 543 / 549.
Missing 6 : {'160490.1.1075.peg', '160490.1.1072_24.peg', '160490.1.1384_8.peg', '160490.1.1073_23.peg', '160490.1.1071_25.peg', '160490.1.1074_22.peg'}

## remove missing genes

In [6]:
# remove missing genes without removing the reaction: 
to_remove = set([g.id for g in Hirose2024.genes]) - added 
to_remove = [Hirose2024.genes.get_by_id(gid) for gid in to_remove]
cobra.manipulation.remove_genes(Hirose2024, to_remove, remove_reactions=False)

print(len(Hirose2024.genes))

543

## save medium recipe

In [9]:
# read the original medium (nutrient-rich THY medium) from the source publication (https://doi.org/10.1128/msystems.00736-24)
original_medium = Hirose2024.medium
print(original_medium)

{'EX_12dgr180_e': 1000.0, 'EX_26dap_M_e': 1000.0, 'EX_ac_e': 1000.0, 'EX_acac_e': 1000.0, 'EX_acald_e': 1000.0, 'EX_acgam_e': 4.6, 'EX_acnam_e': 4.6, 'EX_ala__L_e': 0.46, 'EX_alaasp_e': 0.46, 'EX_alagln_e': 0.46, 'EX_alaglu_e': 0.46, 'EX_alagly_e': 0.46, 'EX_alahis_e': 0.46, 'EX_alaleu_e': 0.46, 'EX_alathr_e': 0.46, 'EX_arab__L_e': 4.6, 'EX_arbt_e': 4.6, 'EX_arg__L_e': 0.46, 'EX_arsenb_e': 1000.0, 'EX_bhb_e': 1000.0, 'EX_btn_e': 1000.0, 'EX_but_e': 1000.0, 'EX_ca2_e': 1000.0, 'EX_cd2_e': 1000.0, 'EX_cellb_e': 4.6, 'EX_cgly_e': 0.46, 'EX_cl_e': 1000.0, 'EX_cobalt2_e': 1000.0, 'EX_ctbt_e': 1000.0, 'EX_cu2_e': 1000.0, 'EX_cys__L_e': 0.46, 'EX_dfdcytd_e': 1000.0, 'EX_dfduri_e': 1000.0, 'EX_etoh_e': 1000.0, 'EX_fe2_e': 1000.0, 'EX_fe3_e': 1000.0, 'EX_fecrm_e': 1000.0, 'EX_fol_e': 1000.0, 'EX_for_e': 1000.0, 'EX_fru_e': 4.6, 'EX_gal_e': 4.6, 'EX_galt_e': 4.6, 'EX_gam_e': 4.6, 'EX_gbbtn_e': 1000.0, 'EX_glc__D_e': 4.6, 'EX_gln__L_e': 0.46, 'EX_glyasn_e': 0.46, 'EX_glyasp_e': 0.46, 'EX_glyb_e': 0.46, 'EX_glyc_e': 4.6, 'EX_glyc3p_e': 4.6, 'EX_glycys_e': 0.46, 'EX_glygln_e': 0.46, 'EX_glyglu_e': 0.46, 'EX_glyleu_e': 0.46, 'EX_glymet_e': 0.46, 'EX_glyphe_e': 0.46, 'EX_glypro_e': 0.46, 'EX_glytyr_e': 0.46, 'EX_h_e': 1000.0, 'EX_h2o_e': 1000.0, 'EX_hg2_e': 1000.0, 'EX_his__L_e': 0.46, 'EX_ile__L_e': 0.46, 'EX_k_e': 1000.0, 'EX_lac__L_e': 5.5, 'EX_lactl_e': 4.6, 'EX_lcts_e': 4.6, 'EX_leu__L_e': 0.46, 'EX_lys__L_e': 0.46, 'EX_malt_e': 4.6, 'EX_malthx_e': 4.6, 'EX_malttr_e': 4.6, 'EX_man_e': 4.6, 'EX_met__D_e': 0.46, 'EX_met__L_e': 0.46, 'EX_metala_e': 0.46, 'EX_metsox_R__L_e': 0.46, 'EX_metsox_S__L_e': 0.46, 'EX_mg2_e': 1000.0, 'EX_mn2_e': 1000.0, 'EX_mnl_e': 4.6, 'EX_mqn7_e': 1000.0, 'EX_na1_e': 1000.0, 'EX_nh4_e': 1000.0, 'EX_nmn_e': 1000.0, 'EX_no2_e': 1000.0, 'EX_o2_e': 20.0, 'EX_orn_e': 0.46, 'EX_pb_e': 1000.0, 'EX_phe__L_e': 0.46, 'EX_pheme_e': 1000.0, 'EX_pi_e': 1000.0, 'EX_pnto__R_e': 1000.0, 'EX_pro__L_e': 0.46, 'EX_ptrc_e': 1000.0, 'EX_ribflv_e': 1000.0, 'EX_salcn_e': 4.6, 'EX_sbt__D_e': 4.6, 'EX_ser__L_e': 0.46, 'EX_sheme_e': 1000.0, 'EX_so4_e': 1000.0, 'EX_spmd_e': 1000.0, 'EX_sucr_e': 4.6, 'EX_thm_e': 1000.0, 'EX_thr__L_e': 0.46, 'EX_tre_e': 4.6, 'EX_trp__L_e': 0.46, 'EX_tyr__L_e': 0.46, 'EX_ura_e': 1000.0, 'EX_val__L_e': 0.46, 'EX_xan_e': 1000.0, 'EX_zn2_e': 1000.0, 'EX_nac_e': 1000.0, 'EX_ade_e': 1000.0, 'EX_gua_e': 1000.0, 'EX_pydam_e': 1000.0, 'EX_pydxn_e': 1000.0, 'EX_asp__L_e': 0.46, 'EX_ins_e': 1000.0, 'EX_hco3_e': 1000.0, 'EX_gly_e': 0.46, 'EX_actn__R_e': 4.6, 'EX_thymd_e': 1000.0, 'EX_asn__L_e': 0.46, 'EX_glu__L_e': 0.46, 'EX_4abz_e': 1000.0, 'EX_orot_e': 1000.0, 'EX_cit_e': 1000.0, 'EX_ascb__L_e': 4.6, 'EX_leuval_e': 0.46, 'EX_ileasp_e': 0.46, 'EX_cbi_e': 1000.0, 'EX_nadp_e': 1000.0, 'EX_all__D_e': 4.6, 'EX_arab__D_e': 4.6, 'EX_cyclodext_A_e': 4.6, 'EX_cyclodext_B_e': 4.6, 'EX_cyclodext_G_e': 4.6, 'EX_pectin_e': 4.6, 'EX_dha_e': 4.6, 'EX_drib_e': 4.6, 'EX_f6p_e': 4.6, 'EX_glcn__D_e': 4.6, 'EX_glycogen_e': 4.6, 'EX_mbdg_e': 4.6, 'EX_pala_e': 4.6, 'EX_rmn_e': 4.6, 'EX_xyl__D_e': 4.6, 'EX_acmana_e': 4.6, 'EX_lyx__L_e': 4.6, 'EX_g6p_e': 4.6, 'EX_glcur_e': 4.6, 'EX_galur_e': 4.6, 'EX_rib__D_e': 4.6, 'EX_uri_e': 4.6, 'EX_adn_e': 4.6, 'EX_fuc__L_e': 4.6, 'EX_tag__D_e': 4.6, 'EX_srb__L_e': 4.6}

In [11]:
# save the recipe for gap-filling
# for gempipe 
save_recipe(Hirose2024, flavour='gempipe', medium_id='medium_gempipe', outpath='04_streptococcus/reference/')
# for bactabolize
save_recipe(Hirose2024, flavour='bactabolize', medium_id='medium_bactabolize', outpath='04_streptococcus/reference/')

In [12]:
# remove medium indredients not present in the universe: 

carveme_uni_pos = gempipe.get_universe(staining='pos')
Hirose2024_carveme_medium = Hirose2024.copy()
for exr_id, value in original_medium.items():
    if exr_id not in [r.id for r in carveme_uni_pos.reactions]: 
        print(exr_id, 'is missing from the CarveMe universe! Will be removed from the medium ingredients.')
        Hirose2024_carveme_medium.reactions.get_by_id(exr_id).bounds = (0, 1000)

EX_26dap_M_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_alaasp_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_alagln_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_alaglu_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_arsenb_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cd2_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_dfdcytd_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_dfduri_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_fecrm_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_gbbtn_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glyasn_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glyasp_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glycys_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glyleu_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glypro_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glytyr_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_hg2_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_lactl_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_metala_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_mqn7_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_na1_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_pb_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_leuval_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_ileasp_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cbi_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_nadp_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cyclodext_A_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cyclodext_B_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cyclodext_G_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_pectin_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_glycogen_e is missing from the CarveMe universe! Will be removed from the medium ingredients.

In [13]:
# for gempipe_rf
save_recipe(Hirose2024_carveme_medium, flavour='gempipe', medium_id='medium_gempipe_rf', outpath='04_streptococcus/reference/')
# for carveme
save_recipe(Hirose2024_carveme_medium, flavour='carveme', medium_id='medium_carveme', outpath='04_streptococcus/reference/')

In [14]:
# for gapseq

# The strategy is to convert the 'original_medium' recipe using SEED ids.
# Duplicated ingredients will be manually removed (see 'medium_gapseq_dedup.csv'). 

with open('seed_mappings/seed_to_others_M.pickle', 'rb') as f:
    seed_to_others_M = pickle.load(f)
    
df_medium_gapseq = []
for exr_id, value in original_medium.items():
    mid = exr_id[3:-2]
    for key, value2 in seed_to_others_M.items():
        if mid in value2['bigg.metabolite']:
            name = Hirose2024.metabolites.get_by_id(f"{mid}_e").name
            df_medium_gapseq.append({'compounds': key, 'name': f"{mid}: {name}", 'maxFlux': value})
df_medium_gapseq = pnd.DataFrame.from_records(df_medium_gapseq)
df_medium_gapseq.to_csv('04_streptococcus/reference/medium_gapseq.csv', index=False)
df_medium_gapseq

    compounds                                               name  maxFlux
0    cpd15311  12dgr180: 1,2-Diacyl-sn-glycerol (dioctadecano...   1000.0
1    cpd00029                                        ac: Acetate   1000.0
2    cpd00142                                 acac: Acetoacetate   1000.0
3    cpd00071                                acald: Acetaldehyde   1000.0
4    cpd00122                      acgam: N-acetyl-D-glucosamine      4.6
..        ...                                                ...      ...
148  cpd00182                                     adn: Adenosine      4.6
149  cpd00751                                   fuc__L: L-Fucose      4.6
150  cpd22637                                   fuc__L: L-Fucose      4.6
151  cpd27358                                   fuc__L: L-Fucose      4.6
152  cpd00589                                 tag__D: D-Tagatose      4.6

[153 rows x 3 columns]

## restore stoichiometric consistency

In [15]:
# launch the memote function: 
un_mids = [m.id for m in find_unconserved_metabolites(Hirose2024)]
print(len(un_mids), sorted(un_mids))

138 ['12dgr120_c', '12dgr140_c', '12dgr141_c', '12dgr160_c', '12dgr161_c', '12dgr180_c', '12dgr180_e', '12dgr181_c', '12dixdglyc_c', '2ddglcn_c', '2ohph_c', '2oph_c', '3dhq_c', '3dhsk_c', '3ophb_c', '4hbz_c', '5drib_c', 'abt_c', 'ac_c', 'ac_e', 'acac_c', 'acac_e', 'acald_c', 'acald_e', 'actn__R_c', 'actn__R_e', 'all__D_c', 'all__D_e', 'altrn_c', 'arab__D_c', 'arab__D_e', 'arab__L_c', 'arab__L_e', 'ascb__L_e', 'bhb_c', 'bhb_e', 'cellb_c', 'cellb_e', 'chor_c', 'cit_c', 'cit_e', 'co2_c', 'co2_e', 'cyclodext_A_c', 'cyclodext_A_e', 'cyclodext_B_c', 'cyclodext_B_e', 'cyclodext_G_c', 'cyclodext_G_e', 'dha_c', 'dha_e', 'diglcpg180_c', 'drib_c', 'drib_e', 'etoh_c', 'etoh_e', 'fa6_c', 'for_c', 'for_e', 'fru_c', 'fru_e', 'fruur_c', 'gal_c', 'gal_e', 'galur_c', 'galur_e', 'glc__D_c', 'glc__D_e', 'glc_b_D_c', 'glcn__D_c', 'glcn__D_e', 'glcur_c', 'glcur_e', 'glyald_c', 'glyc__R_c', 'glyc_c', 'glyc_e', 'glycogen_c', 'glycogen_e', 'h2o2_c', 'h2o_c', 'h2o_e', 'h_c', 'h_e', 'hco3_c', 'hco3_e', 'hdca_c', 'lac__D_c', 'lac__L_c', 'lac__L_e', 'lactl_e', 'lcts_c', 'lcts_e', 'lyx__L_c', 'lyx__L_e', 'm12dsglyc_c', 'mal__L_c', 'malt_c', 'malt_e', 'malthp_c', 'malthx_c', 'malthx_e', 'maltpt_c', 'malttr_c', 'malttr_e', 'maltttr_c', 'man_e', 'mana_c', 'mev__R_c', 'mthgxl_c', 'o2_c', 'o2_e', 'o2s_c', 'oaa_c', 'ocdca_c', 'pala_c', 'pala_e', 'pectin_e', 'pyr_c', 'rbl__D_c', 'rbl__L_c', 'rib__D_c', 'rib__D_e', 'sbt__D_e', 'skm_c', 'srb__L_e', 'starch_e', 'sucr_c', 'sucr_e', 'tag__D_c', 'tag__D_e', 'tagur_c', 'tre_e', 'ttdca_c', 'xyl__D_c', 'xyl__D_e', 'xylu__D_c', 'xylu__L_c']

In [16]:
# remove reactionns ruining stoichoietric consistency:
incriminated = [
    'MALTHPPL', 
    'MALTHXPL', 
    'MALTPTPL', 
    'MALTTRPL', 
    'MALTTTRPL',

    'MALTpts',

    'MLTP1',
    'MLTP2',
    'MLTP3',
]

Hirose2024 = Hirose2024.copy()
Hirose2024.remove_reactions([r for r in Hirose2024.reactions if r.id in incriminated])

# launch the memote function again without the incriminated reactions:
un_mids = [m.id for m in find_unconserved_metabolites(Hirose2024)]
print(len(un_mids), sorted(un_mids))

0 []

## check ATPM

In [17]:
# NGAM is not set in this model:

for r in Hirose2024.reactions:
    if set([m.id for m in r.metabolites]) == set(['atp_c', 'h2o_c', 'adp_c', 'pi_c', 'h_c']):
        print(r.id, r.reaction, r.bounds)

sink_atp_c atp_c + h2o_c --> adp_c + h_c + pi_c (0.0, 1000.0)

## remove strain-specific biom precursors

In [18]:
# According to https://doi.org/10.1128/jb.00837-07 ,
# rhamnose (dtdprmn_c) is a strain specific biomass precursor for S.pneumoniae.

rstring = Hirose2024.reactions.bio1.reaction
rstring = rstring.replace(' + 0.003224799 dtdprmn_c', '')
Hirose2024.reactions.bio1.build_reaction_from_string(rstring)

## save edited version

In [20]:
gempipe.sanity_report(Hirose2024)

gempipe v1.38.2 - sanity_report
model ID: iYH543_20240105
G: 543 R: 1136 M: 970 uM: 820 groups: 0
Compartments: ['c', 'e']
Biomass assemblies: 1 ['EX_biomass_e']
Objectives: 1 ['bio1']
Optimization: 0.7540032375849974 optimal (cplex)
Unconstrained LB-UB: (-1000.0, 1000.0)
Bad EX_change notation: 0
Sinks/demands: 22
Constrained metabolic: 0
With 'artificial' atoms: 148
Missing formulas - charges: 1 - 970
Mass - charge unbalances: 11 - 0

In [19]:
cobra.io.write_sbml_model(Hirose2024, '04_streptococcus/reference/Hirose2024_edited.xml')
cobra.io.save_json_model(Hirose2024, '04_streptococcus/reference/Hirose2024_edited.json')

# 05_pseudomonas

In [3]:
iSD1509 = cobra.io.read_sbml_model('05_pseudomonas/reference/iSD1509.xml')
gempipe.sanity_report(iSD1509)

https://doi.org/10.1101/2021.03.10.434463 does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id

gempipe v1.38.3 - sanity_report
model ID: iSD1509
G: 1510 R: 2021 M: 1642 uM: 1151 groups: 7
Compartments: ['c', 'e', 'p']
Biomass assemblies: 2 ['BIOMASS_PA14_v27M', 'BIOMASS_PA14_v27M_ANA']
Objectives: 1 ['BIOMASS_PA14_v27M']
Optimization: 1.5908505726730195 optimal (cplex)
Unconstrained LB-UB: (-999999.0, 999999.0)
Bad EX_change notation: 0
Sinks/demands: 0
Constrained metabolic: 1777
With 'artificial' atoms: 105
Missing formulas - charges: 0 - 0
Mass - charge unbalances: 0 - 0

In [4]:
gempipe.reset_unconstrained_bounds(iSD1509)
_ = gempipe.check_constrained_metabolic(iSD1509)

1 : G3PD2i : (-1000, 0.0) : glyc3p_c + nadp_c <-- dhap_c + h_c + nadph_c
2 : PPAKrirr : (-1000, 0.0) : adp_c + ppap_c <-- atp_c + ppa_c
3 : PYDXO : (-1000, 0.0) : 2.0 h2o_c + nh4_c + 0.5 o2_c + pydx_c <-- 2.0 h2o2_c + pydam_c
4 : SULR : (-1000, 0.0) : 3.0 h2o_c + h2s_c + 3.0 nadp_c <-- 5.0 h_c + 3.0 nadph_c + so3_c
5 : ATPM : (8.39, 8.39) : atp_c + h2o_c --> adp_c + h_c + pi_c
6 : rxn13804cyt : (-1000, 0.0) : etoh_c + 2.0 ficytc_c <-- acald_c + 2.0 focytc_c
7 : ACACT5r : (-1000, 0.0) : accoa_c + dcacoa_c <-- 3oddcoa_c + coa_c
8 : PIt7ipp : (-1000, 0.0) : 3.0 na1_p + pi_p <-- 3.0 na1_c + pi_c
9 : OXAtpp : (-1000, 0.0) : h_c + oxa_p <-- h_p + oxa_c
10 : OXFOtex : (-1000, 0.0) : oxa_e <-- oxa_p
11 : GLYCLTtex : (-1000, 0.0) : glyclt_e <-- glyclt_p

## get proteomes

In [5]:
# there's a gene marking spontaneous reactions: 'PA_s0001'

# nucleotidic
added = gb_to_modeled(iSD1509, ['05_pseudomonas/reference/GCA_000014625.1.gbff'], '05_pseudomonas/reference/iSD1509.fna')
# amino acidic
added = gb_to_modeled(iSD1509, ['05_pseudomonas/reference/GCA_000014625.1.gbff'], '05_pseudomonas/reference/iSD1509.faa')

/opt/conda/lib/python3.9/site-packages/Bio/Seq.py:3482: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

Recovered 1509 / 1510.
Missing 1 : {'PA_s0001'}
Recovered 1509 / 1510.
Missing 1 : {'PA_s0001'}

## check ATPM

In [8]:
# check the maintenance:
iSD1509.reactions.get_by_id('ATPM')

## check stoichiometric consistency

In [9]:
# launch the memote function: 
un_mids = [m.id for m in find_unconserved_metabolites(iSD1509)]
print(len(un_mids), sorted(un_mids))

0 []

## save medium recipe

In [8]:
# read the original medium (nutrient-rich LB medium) 
original_medium = iSD1509.medium
print(original_medium)

{'EX_glc__D_e': 10.0, 'EX_h2o_e': 1000, 'EX_h_e': 1000, 'EX_leu__L_e': 10.0, 'EX_ala__L_e': 10.0, 'EX_pi_e': 1000, 'EX_gly_e': 10.0, 'EX_ser__L_e': 10.0, 'EX_thr__L_e': 10.0, 'EX_arg__L_e': 10.0, 'EX_lys__L_e': 10.0, 'EX_asp__L_e': 10.0, 'EX_phe__L_e': 10.0, 'EX_k_e': 1000, 'EX_pro__L_e': 10.0, 'EX_mg2_e': 1000, 'EX_zn2_e': 1000, 'EX_co2_e': 1000, 'EX_csn_e': 10.0, 'EX_cu2_e': 1000, 'EX_o2_e': 20.0, 'EX_glu__L_e': 10.0, 'EX_fe2_e': 1000, 'EX_his__L_e': 10.0, 'EX_ile__L_e': 10.0, 'EX_met__L_e': 10.0, 'EX_so4_e': 1000, 'EX_trp__L_e': 10.0, 'EX_tyr__L_e': 10.0, 'EX_val__L_e': 10.0, 'EX_ura_e': 10.0, 'EX_na1_e': 1000, 'EX_cd2_e': 1000, 'EX_cys__L_e': 10.0, 'EX_thm_e': 10.0, 'EX_dad_5_e': 10.0}

In [9]:
# save the recipe for gap-filling
# for gempipe 
save_recipe(iSD1509, flavour='gempipe', medium_id='medium_gempipe', outpath='05_pseudomonas/reference/')
# for bactabolize
save_recipe(iSD1509, flavour='bactabolize', medium_id='medium_bactabolize', outpath='05_pseudomonas/reference/')

In [10]:
# remove medium indredients not present in the universe: 

carveme_uni_neg = gempipe.get_universe(staining='neg')
iSD1509_carveme_medium = iSD1509.copy()
for exr_id, value in original_medium.items():
    if exr_id not in [r.id for r in carveme_uni_neg.reactions]: 
        print(exr_id, 'is missing from the CarveMe universe! Will be removed from the medium ingredients.')
        iSD1509_carveme_medium.reactions.get_by_id(exr_id).bounds = (0, 1000)

EX_na1_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cd2_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_dad_5_e is missing from the CarveMe universe! Will be removed from the medium ingredients.

In [11]:
# These trace elements are required by the CarveMe universe to grow

iSD1509_carveme_medium.reactions.EX_ca2_e.bounds = (-1000, 1000)
iSD1509_carveme_medium.reactions.EX_cl_e.bounds = (-1000, 1000)
iSD1509_carveme_medium.reactions.EX_mn2_e.bounds = (-1000, 1000)
iSD1509_carveme_medium.reactions.EX_cobalt2_e.bounds = (-1000, 1000)

In [12]:
# for gempipe_rf
save_recipe(iSD1509_carveme_medium, flavour='gempipe', medium_id='medium_gempipe_rf', outpath='05_pseudomonas/reference/')
# for carveme
save_recipe(iSD1509_carveme_medium, flavour='carveme', medium_id='medium_carveme', outpath='05_pseudomonas/reference/')

In [13]:
# for gapseq

# The strategy is to convert the 'original_medium' recipe using SEED ids.
# Duplicated ingredients will be manually removed (see 'medium_gapseq_dedup.csv'). 

with open('seed_mappings/seed_to_others_M.pickle', 'rb') as f:
    seed_to_others_M = pickle.load(f)
    
df_medium_gapseq = []
for exr_id, value in original_medium.items():
    mid = exr_id[3:-2]
    for key, value2 in seed_to_others_M.items():
        if mid in value2['bigg.metabolite']:
            name = iSD1509.metabolites.get_by_id(f"{mid}_e").name
            df_medium_gapseq.append({'compounds': key, 'name': f"{mid}: {name}", 'maxFlux': value})
            

# These trace elements are required by the gapseq universe to grow (as logged by gapseq):
# They are manually added in 'medium_gapseq_dedup.csv'
# Warning in media_check(media.file, mod.orig, seed_x_mets):  
#     Potentially missing compounds in medium: 
#     cpd00030 Mn2+, cpd00063 Ca2+, cpd00099 Cl-, cpd00149 Cobalt, cpd10516 Fe3+   
            
df_medium_gapseq = pnd.DataFrame.from_records(df_medium_gapseq)
df_medium_gapseq.to_csv('05_pseudomonas/reference/medium_gapseq.csv', index=False)
df_medium_gapseq

   compounds                      name  maxFlux
0   cpd00027         glc__D: D-Glucose     10.0
1   cpd00001                  h2o: H2O   1000.0
2   cpd00067                     h: H+   1000.0
3   cpd00035         ala__L: L-Alanine     10.0
4   cpd00009             pi: Phosphate   1000.0
5   cpd27787             pi: Phosphate   1000.0
6   cpd00033              gly: Glycine     10.0
7   cpd00054          ser__L: L-Serine     10.0
8   cpd00161       thr__L: L-Threonine     10.0
9   cpd00051        arg__L: L-Arginine     10.0
10  cpd00039          lys__L: L-Lysine     10.0
11  cpd19182          lys__L: L-Lysine     10.0
12  cpd00041       asp__L: L-Aspartate     10.0
13  cpd00066   phe__L: L-Phenylalanine     10.0
14  cpd00205              k: Potassium   1000.0
15  cpd00129         pro__L: L-Proline     10.0
16  cpd15140         pro__L: L-Proline     10.0
17  cpd00254            mg2: Magnesium   1000.0
18  cpd00034                 zn2: Zinc   1000.0
19  cpd00011                  co2: CO2   1000.0
20  cpd00307             csn: Cytosine     10.0
21  cpd00058                 cu2: Cu2+   1000.0
22  cpd00007                    o2: O2     20.0
23  cpd00023       glu__L: L-Glutamate     10.0
24  cpd10515                 fe2: Fe2+   1000.0
25  cpd00119       his__L: L-Histidine     10.0
26  cpd00572       his__L: L-Histidine     10.0
27  cpd00322      ile__L: L-Isoleucine     10.0
28  cpd15139      ile__L: L-Isoleucine     10.0
29  cpd00060      met__L: L-Methionine     10.0
30  cpd00048              so4: Sulfate   1000.0
31  cpd29301              so4: Sulfate   1000.0
32  cpd00065      trp__L: L-Tryptophan     10.0
33  cpd19007      trp__L: L-Tryptophan     10.0
34  cpd00069        tyr__L: L-Tyrosine     10.0
35  cpd30745        tyr__L: L-Tyrosine     10.0
36  cpd00156          val__L: L-Valine     10.0
37  cpd15141          val__L: L-Valine     10.0
38  cpd00092               ura: Uracil     10.0
39  cpd00971               na1: Sodium   1000.0
40  cpd16174               na1: Sodium   1000.0
41  cpd01012              cd2: Cadmium   1000.0
42  cpd00084        cys__L: L-Cysteine     10.0
43  cpd00305              thm: Thiamin     10.0
44  cpd03091  dad_5: 5'-Deoxyadenosine     10.0

## save edited version

In [14]:
cobra.io.write_sbml_model(iSD1509, '05_pseudomonas/reference/iSD1509_edited.xml')
cobra.io.save_json_model(iSD1509, '05_pseudomonas/reference/iSD1509_edited.json')

# 06_pseudomonas

In [33]:
# reference is the same of 05

iSD1509_M9 = iSD1509.copy()
gempipe.sanity_report(iSD1509_M9)

gempipe v1.38.3 - sanity_report
model ID: iSD1509
G: 1510 R: 2021 M: 1642 uM: 1151 groups: 7
Compartments: ['c', 'e', 'p']
Biomass assemblies: 2 ['BIOMASS_PA14_v27M', 'BIOMASS_PA14_v27M_ANA']
Objectives: 1 ['BIOMASS_PA14_v27M']
Optimization: 1.5908505726730195 optimal (cplex)
Unconstrained LB-UB: (-1000, 1000)
Bad EX_change notation: 0
Sinks/demands: 0
Constrained metabolic: 11
With 'artificial' atoms: 105
Missing formulas - charges: 0 - 0
Mass - charge unbalances: 0 - 0

In [34]:
# remove everything but trace metal ions:

# close complex medium sources:
iSD1509_M9.reactions.EX_leu__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_ala__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_gly_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_ser__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_thr__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_arg__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_lys__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_asp__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_phe__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_pro__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_csn_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_his__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_ile__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_met__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_trp__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_tyr__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_val__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_cys__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_glu__L_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_thm_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_dad_5_e.bounds = (0, 1000)
iSD1509_M9.reactions.EX_ura_e.bounds = (0, 1000)

# open sole N source
iSD1509_M9.reactions.EX_nh4_e.bounds = (-1000, 1000)

iSD1509_M9.medium

{'EX_glc__D_e': 10.0,
 'EX_h2o_e': 1000,
 'EX_h_e': 1000,
 'EX_pi_e': 1000,
 'EX_nh4_e': 1000,
 'EX_k_e': 1000,
 'EX_mg2_e': 1000,
 'EX_zn2_e': 1000,
 'EX_co2_e': 1000,
 'EX_cu2_e': 1000,
 'EX_o2_e': 20.0,
 'EX_fe2_e': 1000,
 'EX_so4_e': 1000,
 'EX_na1_e': 1000,
 'EX_cd2_e': 1000}

In [35]:
gempipe.sanity_report(iSD1509_M9)

gempipe v1.38.3 - sanity_report
model ID: iSD1509
G: 1510 R: 2021 M: 1642 uM: 1151 groups: 7
Compartments: ['c', 'e', 'p']
Biomass assemblies: 2 ['BIOMASS_PA14_v27M', 'BIOMASS_PA14_v27M_ANA']
Objectives: 1 ['BIOMASS_PA14_v27M']
Optimization: 0.894342371582688 optimal (cplex)
Unconstrained LB-UB: (-1000, 1000)
Bad EX_change notation: 0
Sinks/demands: 0
Constrained metabolic: 11
With 'artificial' atoms: 105
Missing formulas - charges: 0 - 0
Mass - charge unbalances: 0 - 0

## save medium recipe

In [37]:
# read the original medium (nutrient-rich LB medium) 
original_medium = iSD1509_M9.medium
print(original_medium)

{'EX_glc__D_e': 10.0, 'EX_h2o_e': 1000, 'EX_h_e': 1000, 'EX_pi_e': 1000, 'EX_nh4_e': 1000, 'EX_k_e': 1000, 'EX_mg2_e': 1000, 'EX_zn2_e': 1000, 'EX_co2_e': 1000, 'EX_cu2_e': 1000, 'EX_o2_e': 20.0, 'EX_fe2_e': 1000, 'EX_so4_e': 1000, 'EX_na1_e': 1000, 'EX_cd2_e': 1000}

In [38]:
# save the recipe for gap-filling
# for gempipe 
save_recipe(iSD1509_M9, flavour='gempipe', medium_id='medium_gempipe', outpath='06_pseudomonas/reference/')
# for bactabolize
save_recipe(iSD1509_M9, flavour='bactabolize', medium_id='medium_bactabolize', outpath='06_pseudomonas/reference/')

In [39]:
# remove medium indredients not present in the universe: 

carveme_uni_neg = gempipe.get_universe(staining='neg')
iSD1509_M9_carveme_medium = iSD1509_M9.copy()
for exr_id, value in original_medium.items():
    if exr_id not in [r.id for r in carveme_uni_neg.reactions]: 
        print(exr_id, 'is missing from the CarveMe universe! Will be removed from the medium ingredients.')
        iSD1509_M9_carveme_medium.reactions.get_by_id(exr_id).bounds = (0, 1000)

EX_na1_e is missing from the CarveMe universe! Will be removed from the medium ingredients.
EX_cd2_e is missing from the CarveMe universe! Will be removed from the medium ingredients.

In [40]:
# These trace elements are required by the CarveMe universe to grow

iSD1509_M9_carveme_medium.reactions.EX_ca2_e.bounds = (-1000, 1000)
iSD1509_M9_carveme_medium.reactions.EX_cl_e.bounds = (-1000, 1000)
iSD1509_M9_carveme_medium.reactions.EX_mn2_e.bounds = (-1000, 1000)
iSD1509_M9_carveme_medium.reactions.EX_cobalt2_e.bounds = (-1000, 1000)

In [41]:
# for gempipe_rf
save_recipe(iSD1509_M9_carveme_medium, flavour='gempipe', medium_id='medium_gempipe_rf', outpath='06_pseudomonas/reference/')
# for carveme
save_recipe(iSD1509_M9_carveme_medium, flavour='carveme', medium_id='medium_carveme', outpath='06_pseudomonas/reference/')

In [42]:
# for gapseq

# The strategy is to convert the 'original_medium' recipe using SEED ids.
# Duplicated ingredients will be manually removed (see 'medium_gapseq_dedup.csv'). 

with open('seed_mappings/seed_to_others_M.pickle', 'rb') as f:
    seed_to_others_M = pickle.load(f)
    
df_medium_gapseq = []
for exr_id, value in original_medium.items():
    mid = exr_id[3:-2]
    for key, value2 in seed_to_others_M.items():
        if mid in value2['bigg.metabolite']:
            name = iSD1509_M9.metabolites.get_by_id(f"{mid}_e").name
            df_medium_gapseq.append({'compounds': key, 'name': f"{mid}: {name}", 'maxFlux': value})
            

# These trace elements are required by the gapseq universe to grow (as logged by gapseq):
# They are manually added in 'medium_gapseq_dedup.csv'
# Warning in media_check(media.file, mod.orig, seed_x_mets):  
#     Potentially missing compounds in medium: 
#     cpd00030 Mn2+, cpd00063 Ca2+, cpd00099 Cl-, cpd00149 Cobalt, cpd10516 Fe3+   
            
df_medium_gapseq = pnd.DataFrame.from_records(df_medium_gapseq)
df_medium_gapseq.to_csv('06_pseudomonas/reference/medium_gapseq.csv', index=False)
df_medium_gapseq

   compounds               name  maxFlux
0   cpd00027  glc__D: D-Glucose     10.0
1   cpd00001           h2o: H2O   1000.0
2   cpd00067              h: H+   1000.0
3   cpd00009      pi: Phosphate   1000.0
4   cpd27787      pi: Phosphate   1000.0
5   cpd00013      nh4: Ammonium   1000.0
6   cpd19013      nh4: Ammonium   1000.0
7   cpd00205       k: Potassium   1000.0
8   cpd00254     mg2: Magnesium   1000.0
9   cpd00034          zn2: Zinc   1000.0
10  cpd00011           co2: CO2   1000.0
11  cpd00058          cu2: Cu2+   1000.0
12  cpd00007             o2: O2     20.0
13  cpd10515          fe2: Fe2+   1000.0
14  cpd00048       so4: Sulfate   1000.0
15  cpd29301       so4: Sulfate   1000.0
16  cpd00971        na1: Sodium   1000.0
17  cpd16174        na1: Sodium   1000.0
18  cpd01012       cd2: Cadmium   1000.0

## save edited version

In [45]:
cobra.io.write_sbml_model(iSD1509_M9, '06_pseudomonas/reference/iSD1509_M9_edited.xml')
cobra.io.save_json_model(iSD1509_M9, '06_pseudomonas/reference/iSD1509_M9_edited.json')

In [46]:
gempipe.sanity_report(iSD1509_M9)

gempipe v1.38.3 - sanity_report
model ID: iSD1509
G: 1510 R: 2021 M: 1642 uM: 1151 groups: 7
Compartments: ['c', 'e', 'p']
Biomass assemblies: 2 ['BIOMASS_PA14_v27M', 'BIOMASS_PA14_v27M_ANA']
Objectives: 1 ['BIOMASS_PA14_v27M']
Optimization: 0.894342371582688 optimal (cplex)
Unconstrained LB-UB: (-1000, 1000)
Bad EX_change notation: 0
Sinks/demands: 0
Constrained metabolic: 11
With 'artificial' atoms: 105
Missing formulas - charges: 0 - 0
Mass - charge unbalances: 0 - 0