In [1]:
import shutil
import glob
import os

import pandas as pnd
from Bio import SeqIO, SeqRecord, SeqFeature, Seq

# 01_klebsiella

In [2]:
# prepare the 37 input genomes:
# mamba update openpyxl
metadata = pnd.read_csv('01_klebsiella/tables/metadata.csv', index_col=0)

metadata['full_name'] = metadata['Species'] + ' '+ metadata['Strain']
metadata['full_name'] = metadata['full_name'].str.replace('K. ', 'Klebsiella ')
metadata.index = metadata.index + 1
metadata = metadata.rename(columns={i: i.lower() for i in metadata.columns})
metadata[['full_name', 'accession']].to_excel('01_klebsiella/tables/genomes.xlsx')

print(metadata.shape)
metadata

(37, 4)

,strain,species,accession,full_name
1,200023T,K. africana,GCA_020526085.1,Klebsiella africana 200023T
2,03-9138-2,K. pneumoniae,GCA_020526045.1,Klebsiella pneumoniae 03-9138-2
3,04A025,K. pneumoniae,GCA_020526025.1,Klebsiella pneumoniae 04A025
4,BJ1,K. pneumoniae,GCA_020526065.1,Klebsiella pneumoniae BJ1
5,CG43,K. pneumoniae,NC_022566.1 + NC_005249.1,Klebsiella pneumoniae CG43
6,CIP 52.145,K. pneumoniae,GCA_000968155.1,Klebsiella pneumoniae CIP 52.145
7,KP13,K. pneumoniae,GCA_000512165.1,Klebsiella pneumoniae KP13
8,MGH 78578,K. pneumoniae,GCF_000016305.1,Klebsiella pneumoniae MGH 78578
9,NJST258-1,K. pneumoniae,GCF_000598005.1,Klebsiella pneumoniae NJST258-1
10,NTUH K2044,K. pneumoniae,GCF_000009885.1,Klebsiella pneumoniae NTUH K2044
11,SA1,K. pneumoniae,GCA_020525885.1,Klebsiella pneumoniae SA1
12,SA12,K. pneumoniae,GCA_020525485.1,Klebsiella pneumoniae SA12
13,SB1067,K. pneumoniae,GCA_020525845.1,Klebsiella pneumoniae SB1067
14,SB1139,K. pneumoniae,GCA_020525505.1,Klebsiella pneumoniae SB1139
15,SB1170,K. pneumoniae,GCA_020525645.1,Klebsiella pneumoniae SB1170
16,SB2390 (=cur15505),K. pneumoniae,GCA_020526005.1,Klebsiella pneumoniae SB2390 (=cur15505)
17,SB611,K. pneumoniae,GCA_020525985.1,Klebsiella pneumoniae SB611
18,SB612,K. pneumoniae,GCA_020525965.1,Klebsiella pneumoniae SB612
19,SB615,K. pneumoniae,GCA_020525945.1,Klebsiella pneumoniae SB615
20,SB617,K. pneumoniae,GCA_020525905.1,Klebsiella pneumoniae SB617
21,T69,K. pneumoniae,GCA_020525865.1,Klebsiella pneumoniae T69
22,01A030T,K. quasipneumoniae subsp quasipneumoniae,GCA_020525925.1,Klebsiella quasipneumoniae subsp quasipneumoni...
23,18A069,K. quasipneumoniae subsp quasipneumoniae,GCA_020525805.1,Klebsiella quasipneumoniae subsp quasipneumoni...
24,SB1124,K. quasipneumoniae subsp quasipneumoniae,GCA_020525825.1,Klebsiella quasipneumoniae subsp quasipneumoni...
25,SB98,K. quasipneumoniae subsp quasipneumoniae,GCA_020525785.1,Klebsiella quasipneumoniae subsp quasipneumoni...
26,U41,K. quasipneumoniae subsp quasipneumoniae,GCA_020525725.1,Klebsiella quasipneumoniae subsp quasipneumoni...
27,07A044T,K. quasipneumoniae subsp similipneumoniae,GCA_020525685.1,Klebsiella quasipneumoniae subsp similipneumon...
28,09A323,K. quasipneumoniae subsp similipneumoniae,GCA_020525585.1,Klebsiella quasipneumoniae subsp similipneumon...
29,12A476,K. quasipneumoniae subsp similipneumoniae,GCA_020525525.1,Klebsiella quasipneumoniae subsp similipneumon...
30,CIP 110288 (= CW-D3),K. quasipneumoniae subsp similipneumoniae,GCA_020525565.1,Klebsiella quasipneumoniae subsp similipneumon...
31,SB610,K. quasipneumoniae subsp similipneumoniae,GCA_020525705.1,Klebsiella quasipneumoniae subsp similipneumon...
32,08A119,K. quasivariicola,GCA_020525665.1,Klebsiella quasivariicola 08A119
33,CDC 4241-71,K. variicola subsp tropica,GCA_020525625.1,Klebsiella variicola subsp tropica CDC 4241-71
34,01A065,K. variicola subsp variicola,GCA_020525605.1,Klebsiella variicola subsp variicola 01A065
35,342,K. variicola subsp variicola,GCF_000019565.1,Klebsiella variicola subsp variicola 342
36,At-22,K. variicola subsp variicola,GCF_000025465.1,Klebsiella variicola subsp variicola At-22
37,F2R9T,K. variicola subsp variicola,GCA_020525545.1,Klebsiella variicola subsp variicola F2R9T

In [3]:
# create a folder containing the input genomes, 
# having as filename the strain ID instead of the assemlby accession.

for index, row in metadata.iterrows():
    # get the assembly file
    if row['accession'] == 'NC_022566.1 + NC_005249.1' : 
        assembly = '01_klebsiella/genomes/NC_022566.1_NC_005249.1.fasta'
    else: assembly = '01_klebsiella/genomes/' + row['accession'] + '.fna'
    # get the strain name
    species = row['species']
    if   species == 'K. africana': species = 'Ka'
    elif species == 'K. pneumoniae': species = 'Kp'
    elif species == 'K. quasipneumoniae subsp quasipneumoniae': species = 'Kqq'
    elif species == 'K. quasipneumoniae subsp similipneumoniae': species = 'Kqs'
    elif species == 'K. quasivariicola': species = 'Kqv'
    elif species == 'K. variicola subsp tropica': species = 'Kvt'
    elif species == 'K. variicola subsp variicola': species = 'Kvv'
    strain = str(row['strain'])
    if ' (=' in strain: strain = strain.split(' (=', 1)[0]
    strain  = strain.replace(' ', '').replace('-', '_')
    shutil.copyfile(assembly, f'01_klebsiella/genomes_renamed/{species}_{strain}.fna')

# 02_ralstonia

In [4]:
metadata = pnd.read_csv('02_ralstonia/tables/metadata.csv', index_col=0)
metadata.index = metadata.reset_index(drop=True).index + 1
metadata = metadata.rename(columns={i: i.lower() for i in metadata.columns})

metadata['full_name'] = metadata['species'] + ' ' + metadata['strain']
metadata['full_name'] = metadata['full_name'].str.replace('R. ', 'Ralstonia ')

metadata[['full_name', 'accession']].to_excel('02_ralstonia/tables/genomes.xlsx')
metadata

,strain,phylotype,species,accession,full_name
1,GMI1000,I,R. pseudosolanacearum,GCA_029220065.1,Ralstonia pseudosolanacearum GMI1000
2,PSS4,I,R. pseudosolanacearum,GCA_029220045.1,Ralstonia pseudosolanacearum PSS4
3,RUN2340,III,R. pseudosolanacearum,GCA_029220025.1,Ralstonia pseudosolanacearum RUN2340
4,CFBP2957,IIA,R. solanacearum,GCA_029220005.1,Ralstonia solanacearum CFBP2957
5,K60,IIA,R. solanacearum,GCA_029219985.1,Ralstonia solanacearum K60
6,BA7,IIA,R. solanacearum,GCA_029219965.1,Ralstonia solanacearum BA7
7,UW551,IIB,R. solanacearum,GCA_029219945.1,Ralstonia solanacearum UW551
8,MOLK2,IIB,R. solanacearum,GCF_000009125.1,Ralstonia solanacearum MOLK2
9,PSI07,IV,R. syzygii,GCF_002251695.1,Ralstonia syzygii PSI07
10,R24,IV,R. syzygii,GCF_002251655.1,Ralstonia syzygii R24
11,BDBR229,IV,R. syzygii,GCF_000283475.1,Ralstonia syzygii BDBR229

In [5]:
# create a folder containing the input genomes, 
# having as filename the strain ID instead of the assemlby accession.

for file in glob.glob('02_ralstonia/genomes/*fna'):
    accession = file.replace('02_ralstonia/genomes/', '')
    accession = '_'.join(accession.split('_')[:2])
    match = metadata[metadata['accession']==accession].iloc[0]
    renamed = match['strain'] + '.fna'
    shutil.copyfile(file, '02_ralstonia/genomes_renamed/' + renamed)

# 03_pseudomonas

In [6]:
metadata = pnd.read_csv('03_pseudomonas/tables/metadata.csv', index_col=0)
metadata.index = metadata.reset_index(drop=True).index + 1
metadata = metadata.rename(columns={i: i.lower() for i in metadata.columns})
metadata = metadata.rename(columns={'phylogenetic subgroups': 'full_name'})
metadata[['full_name', 'accession']].to_excel('03_pseudomonas/tables/genomes.xlsx')
metadata

,full_name,accession number,strain,accession,notes
1,Pseudomonas chlororaphis 30-84,NZ_CM001559,30-84,GCF_000281915.1,NaN
2,Pseudomonas chlororaphis ATCC17415,CP027714,ATCC17415,GCF_003851145.1,NaN
3,Pseudomonas chlororaphis TAMOak81,CP027713,TAMOak81,GCF_003850605.1,NaN
4,Pseudomonas chlororaphis subsp. piscium ATCC17411,CP027708,ATCC17411,GCF_003850385.1,NaN
5,Pseudomonas chlororaphis subsp. piscium ATCC17809,CP027709,ATCC17809,GCF_003850365.1,NaN
6,Pseudomonas chlororaphis subsp. piscium ChPhzS135,CP027738,ChPhzS135,GCF_003850485.1,NaN
7,Pseudomonas chlororaphis subsp. piscium DTR133,CP027735,DTR133,GCF_003850425.1,NaN
8,Pseudomonas chlororaphis subsp. piscium SLPH10,CP027710,SLPH10,GCF_003850405.1,NaN
9,Pseudomonas chlororaphis subsp. piscium ToZa7,CP027739,ToZa7,GCF_003850585.1,NaN
10,Pseudomonas chlororaphis subsp. piscium ChPhzTR44,CP027711,ChPhzTR44,GCF_003850525.1,NaN
11,Pseudomonas chlororaphis subsp. piscium ChPhzS140,CP027740,ChPhzS140,GCF_003850505.1,NaN
12,Pseudomonas chlororaphis subsp. piscium PCL1607,CP027737,PCL1607,GCF_003850465.1,NaN
13,Pseudomonas chlororaphis subsp. piscium PCL1391,CP027736,PCL1391,GCF_003850445.1,NaN
14,Pseudomonas chlororaphis subsp. piscium DSM 21509,CP027707,DSM 21509,GCF_003850345.1,NaN
15,Pseudomonas chlororaphis B25,CP027753,B25,GCF_003851985.1,NaN
16,Pseudomonas chlororaphis Pb-St2,CP027716,Pb-St2,GCF_003851785.1,NaN
17,Pseudomonas chlororaphis subsp. aurantiaca CW2,CP027743,CW2,GCF_003851225.1,NaN
18,Pseudomonas chlororaphis subsp. aurantiaca 449,CP027741,449,GCF_003851205.1,NaN
19,Pseudomonas chlororaphis subsp. aurantiaca 464,CP027742,464,GCF_003851805.1,NaN
20,Pseudomonas chlororaphis subsp. aurantiaca DS...,CP027746,DSM 19603,GCF_003851835.1,NaN
21,Pseudomonas chlororaphis subsp. aurantiaca PC...,CP027717,PCM2210,GCF_003851305.1,NaN
22,Pseudomonas chlororaphis subsp. aurantiaca Q16,CP027718,Q16,GCF_003851345.1,NaN
23,Pseudomonas chlororaphis subsp. aurantiaca M12,CP027715,M12,GCF_003851165.1,NaN
24,Pseudomonas chlororaphis subsp. aurantiaca K27,CP027745,K27,GCA_003851285.1,many frameshifted proteins
25,Pseudomonas chlororaphis subsp. aurantiaca M71,CP027744,M71,GCF_003851265.1,NaN
26,Pseudomonas chlororaphis subsp. aureofaciens P2,CP027719,P2,GCF_003851365.1,NaN
27,Pseudomonas chlororaphis subsp. aureofaciens C50,CP027722,C50,GCF_003851385.1,NaN
28,Pseudomonas chlororaphis subsp. aureofaciens ...,CP027720,DSM 6698,GCF_003851905.1,NaN
29,Pseudomonas chlororaphis subsp. aureofaciens C...,CP027748,ChPhzS23,GCA_003851425.1,many frameshifted proteins
30,Pseudomonas chlororaphis subsp. aureofaciens 66,CP027747,66,GCF_003851405.1,NaN
31,Pseudomonas chlororaphis subsp. aureofaciens C...,CP027750,ChPhzS24,GCF_003851445.1,NaN
32,Pseudomonas chlororaphis subsp. aureofaciens C...,CP027752,ChPhzTR38,GCF_003852005.1,NaN
33,Pseudomonas chlororaphis subsp. aureofaciens C...,CP027749,ChPhzTR39,GCF_003851925.1,NaN
34,Pseudomonas chlororaphis subsp. aureofaciens C...,CP027751,ChPhzTR18,GCF_003851955.1,NaN
35,Pseudomonas chlororaphis subsp. aureofaciens PA23,CP008696,PA23,GCF_000698865.1,NaN
36,Pseudomonas chlororaphis subsp. aureofaciens O6,NZ_CM001490,O6,GCF_000264555.1,NaN

In [7]:
# create a folder containing the input genomes, 
# having as filename the strain ID instead of the assemlby accession.

for file in glob.glob('03_pseudomonas/genomes/*fna'):
    accession = file.replace('03_pseudomonas/genomes/', '')
    accession = '_'.join(accession.split('_')[:2])
    match = metadata[metadata['accession']==accession].iloc[0]
    renamed = str(match['strain']) + '.fna'
    renamed = renamed.replace(' ', '_')
    shutil.copyfile(file, '03_pseudomonas/genomes_renamed/' + renamed)

# 04_streptococcus

In [2]:
SD1 = pnd.read_excel('04_streptococcus/tables/41564_2022_1208_MOESM4_ESM.xlsx', sheet_name='Supplementary_data_1')
SD1.head()

,Strain name,Common lab name,Serotype,GPS Cluster1,Bioproject PRJNA514780 biosample accesion,GenBank accession,Collection date,Collection location,Source,Original accesion,Original strain name,Transformability,Transformation efficiency fold2,Tn-Seq libraries saturation (%)3
0,TVO_1901920,PG01,23F,7,SAMN10734509,CP035265,2006,Netherlands: Nijmegen,Blood,ERS225747,2363STDY5509399,High,3x,75.0
1,TVO_1901921,PG02,23F,7,SAMN10734510,CP035264,2004,Netherlands: Nijmegen,Blood,ERS225676,2363STDY5509327,High,3x,69.0
2,TVO_1901922,PG03,14,18,SAMN10734511,CP035263,2009,Netherlands: Nijmegen,Blood,ERS225879,2363STDY5509533,Null,0x,0.0
3,TVO_1901923,PG04,14,18,SAMN10734512,CP035262,2001,Netherlands: Nijmegen,Blood,ERS225592,2363STDY5509243,High,3x,80.0
4,TVO_1901924,PG05,33A/F,3,SAMN10734513,CP035261,2003,Netherlands: Nijmegen,Blood,ERS225628,2363STDY5509279,Null,0x,0.0

In [3]:
high_saturation = SD1[SD1['Tn-Seq libraries saturation (%)3']>35]
high_saturation = high_saturation.set_index('GenBank accession', drop=True)
high_saturation

,Strain name,Common lab name,Serotype,GPS Cluster1,Bioproject PRJNA514780 biosample accesion,Collection date,Collection location,Source,Original accesion,Original strain name,Transformability,Transformation efficiency fold2,Tn-Seq libraries saturation (%)3
GenBank accession,,,,,,,,,,,,,
CP035265,TVO_1901920,PG01,23F,7,SAMN10734509,2006,Netherlands: Nijmegen,Blood,ERS225747,2363STDY5509399,High,3x,75.0
CP035264,TVO_1901921,PG02,23F,7,SAMN10734510,2004,Netherlands: Nijmegen,Blood,ERS225676,2363STDY5509327,High,3x,69.0
CP035262,TVO_1901923,PG04,14,18,SAMN10734512,2001,Netherlands: Nijmegen,Blood,ERS225592,2363STDY5509243,High,3x,80.0
CP035260,TVO_1901925,PG06,33A/F,3,SAMN10734514,2008,Netherlands: Nijmegen,Blood,ERS225816,2363STDY5509469,High,3x,62.0
CP035255,TVO_1901931,PG12,6B,24,SAMN10734519,2008,Netherlands: Nijmegen,Blood,ERS225831,2363STDY5509484,Medium,1x,50.0
CP035254,TVO_1901932,PG13,6C,89,SAMN10734520,2008,Netherlands: Nijmegen,Blood,ERS225829,2363STDY5509482,Medium,1x,55.0
CP035252,TVO_1901934,PG15,19A,4,SAMN10734522,2010,Netherlands: Nijmegen,Blood,ERS225891,2363STDY5509545,Medium,1x,62.0
CP035251,TVO_1901935,PG16,19A,4,SAMN10734523,2008,Netherlands: Nijmegen,Blood,ERS225826,2363STDY5509479,High,3x,66.0
CP038251,TVO_1901944,PG25,22A/F,19,SAMN10734565,2004,Netherlands: Nijmegen,Blood,ERS225678,2363STDY5509330,High,3x,64.0
CP035243,TVO_1901946,PG27,35B,36,SAMN10734531,2008,Netherlands: Nijmegen,Blood,ERS225834,2363STDY5509487,High,1x,53.0
CP035242,TVO_1901947,PG28,35B,36,SAMN10734532,2009,Netherlands: Nijmegen,Blood,ERS225877,2363STDY5509531,High,3x,66.0
CP035241,TVO_1901948,PG29,8,3,SAMN10734533,2008,Netherlands: Nijmegen,Blood,ERS225821,2363STDY5509474,Low,0.1x,53.0
CP035239,TVO_TIGR4,TIGR4-AC316,4,27,SAMN10734535,missing,Norway: Konsvinger,Blood,SAMN00103527,TIGR4,High,1x,63.0
CP035238,TVO_D39,D39-AC1770,2,622,SAMN10734536,missing,missing,Missing,SAMN02604051,D39,High,1.5x,61.0
CP035237,TVO_Taiwan19F-14,Taiwan19F-14,19F,1,SAMN10734537,missing,Taiwan,Cerebrospinal fluid,SAMN02603443,Taiwan19F-14,High,6x,65.0
CP035236,TVO_1902282,BHN97,19F,175,SAMN10734538,1997,Sweden: Stockholm,Nasopharynx,SAMN08105887,BHN97,High,6x,76.0
CP035235,TVO_1902276,CT22F,22F,19,SAMN10734539,missing,USA: Connecticut,Blood,missing,ABC020079715,High,1.5x,63.0

In [4]:
SD6 = pnd.read_excel('04_streptococcus/tables/41564_2022_1208_MOESM4_ESM.xlsx', sheet_name='Supplementary_data_6')
SD6.head()

,Cluster,Subcluster,Strain,Genome,locus_tag,Gene product,TA sites with insertions,Total TA sites,Binomial z value,Binomial Call,Length,Feature counts Replicate 1,Feature counts Replicate 2,Feature counts Replicate 3,Log2 Mean of TPM normalized Feature counts,SD of Log2 Mean of TPM normalized Feature counts
0,2080.0,2080_0,PG01,CP035265,EQH15_00005,chromosomal replication initiator protein DnaA,3.0,88.0,1.0000,Essential,1362,2349,685,1523,7.439561,0.098540
1,1139.0,1139_0,PG01,CP035265,EQH15_00010,DNA polymerase III subunit beta,2.0,64.0,1.0000,Essential,1137,2862,840,1813,7.976964,0.081080
2,1518.0,1518_0,PG01,CP035265,EQH15_00015,DUF951 family protein,0.0,9.0,1.0000,Essential,195,73,26,48,5.338654,0.072572
3,640.0,640_0,PG01,CP035265,EQH15_00020,redox-regulated ATPase YchF,34.0,48.0,0.0284,Non-Essential,1116,1728,486,1009,7.216257,0.097997
4,260.0,260_0,PG01,CP035265,EQH15_00025,aminoacyl-tRNA hydrolase,2.0,35.0,1.0000,Essential,570,205,54,101,4.996950,0.187597

In [11]:


os.makedirs('04_streptococcus/proteomes_renamed/', exist_ok=True)


metadata = []
proteomes_raw = glob.glob('04_streptococcus/proteomes/*.1.faa')
for file in proteomes_raw:
    accession_ori = file.replace('04_streptococcus/proteomes/', '').replace('.1.faa', '')
    accession = accession_ori + '.1'
    strain_lab_name = high_saturation.loc[accession_ori, 'Common lab name']
    full_name = 'Streptococcus pneumoniae ' + strain_lab_name
    metadata.append({'full_name': full_name, 'accession': accession})
    output_file = f'04_streptococcus/proteomes_renamed/{strain_lab_name}.faa'
    records = []
    ids_added = set()
    for i, record in enumerate(SeqIO.parse(file, "fasta")):
        new_id = record.description.split('[locus_tag=',1)[-1].split(']', 1)[0]
        ids_added.add(new_id)
        record.id = new_id
        record.description = ""  
        
        # handle eventual asterisks and dashes:
        cnt_asterisks = record.seq.count("*")
        cnt_dashes = record.seq.count("-")
        record.seq = record.seq.rstrip("*")
        record.seq = record.seq.replace("*", "X")
        record.seq = record.seq.replace("-", '')
        records.append(record)
    
    SeqIO.write(records, output_file, "fasta")
    mentioned = set(SD6[SD6['Genome']==accession_ori]['locus_tag'].to_list())
    missing = mentioned - set(ids_added)
    print(f"Written '{output_file}'. Mentioned: {len(mentioned)}. Added: {len(ids_added)}. Missing sequences: {len(missing)}.")
    
metadata = pnd.DataFrame.from_records(metadata)

Written '04_streptococcus/proteomes_renamed/PG04.faa'. Mentioned: 2107. Added: 2172. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG16.faa'. Mentioned: 2149. Added: 2165. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG27.faa'. Mentioned: 2024. Added: 2209. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG29.faa'. Mentioned: 2038. Added: 2071. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG01.faa'. Mentioned: 2163. Added: 2186. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG13.faa'. Mentioned: 2181. Added: 2194. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG15.faa'. Mentioned: 2258. Added: 2276. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG02.faa'. Mentioned: 2207. Added: 2241. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/D39-AC1770.faa'. Mentioned: 2081. Added: 2116. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG12.faa'. Mentioned: 2237. Added: 2254. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/Taiwan19F-14.faa'. Mentioned: 2171. Added: 2191. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/CT22F.faa'. Mentioned: 2192. Added: 2237. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG06.faa'. Mentioned: 2052. Added: 2071. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG25.faa'. Mentioned: 2129. Added: 2147. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/BHN97.faa'. Mentioned: 2154. Added: 2177. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/TIGR4-AC316.faa'. Mentioned: 1750. Added: 2235. Missing sequences: 0.
Written '04_streptococcus/proteomes_renamed/PG28.faa'. Mentioned: 1655. Added: 2201. Missing sequences: 0.

In [13]:
os.makedirs('04_streptococcus/tables/', exist_ok=True)
metadata[['full_name', 'accession']].to_excel('04_streptococcus/tables/genomes.xlsx')
metadata

                                full_name   accession
0           Streptococcus pneumoniae PG04  CP035262.1
1           Streptococcus pneumoniae PG16  CP035251.1
2           Streptococcus pneumoniae PG27  CP035243.1
3           Streptococcus pneumoniae PG29  CP035241.1
4           Streptococcus pneumoniae PG01  CP035265.1
5           Streptococcus pneumoniae PG13  CP035254.1
6           Streptococcus pneumoniae PG15  CP035252.1
7           Streptococcus pneumoniae PG02  CP035264.1
8     Streptococcus pneumoniae D39-AC1770  CP035238.1
9           Streptococcus pneumoniae PG12  CP035255.1
10  Streptococcus pneumoniae Taiwan19F-14  CP035237.1
11         Streptococcus pneumoniae CT22F  CP035235.1
12          Streptococcus pneumoniae PG06  CP035260.1
13          Streptococcus pneumoniae PG25  CP038251.1
14         Streptococcus pneumoniae BHN97  CP035236.1
15   Streptococcus pneumoniae TIGR4-AC316  CP035239.1
16          Streptococcus pneumoniae PG28  CP035242.1

# 05 / 06 pseudomonas

In [15]:


suppl_table_03 = pnd.read_excel('05_pseudomonas/tables/pnas.1900570116.sd03.xlsx')
suppl_table_03 = suppl_table_03.set_index('Gene ID', drop=True, verify_integrity=True)
# format strain names
for index, row in suppl_table_03.iterrows():
    if row['Strain'] == 'BWH005': suppl_table_03.loc[index, 'Strain'] = 'BWHPSA005'
    if row['Strain'] == 'BWH013': suppl_table_03.loc[index, 'Strain'] = 'BWHPSA013'
    if row['Strain'] == 'BWH015': suppl_table_03.loc[index, 'Strain'] = 'BWHPSA015'
    if row['Strain'] == 'PA14': suppl_table_03.loc[index, 'Strain'] = 'UCBPP-PA14'

suppl_table_03

,Strain,LB Essential Call (FWER-adjustment),LB Essential Call (FDR-adjustment),LB Essential Call (TRANSIT HMM),M9 Essential Call (FWER-adjustment),M9 Essential Call (FDR-adjustment),M9 Essential Call (TRANSIT HMM)
Gene ID,,,,,,,
Q018_00033,BWHPSA005,NE,NE,GA,NE,NE,NE
Q018_00046,BWHPSA005,NE,NE,GA,NE,NE,NE
Q018_00051,BWHPSA005,NE,NE,GA,NE,NE,NE
Q018_00063,BWHPSA005,NE,NE,GA,NE,NE,NE
Q018_00076,BWHPSA005,NE,NE,GA,NE,NE,NE
...,...,...,...,...,...,...,...
Q026_04217,BWHPSA013,E,E,ES,E,E,ES
Q026_02953,BWHPSA013,NE,NE,NE,NE,NE,NE
Q026_02893,BWHPSA013,NE,E,NE,NE,NE,NE
Q026_01136,BWHPSA013,NE,E,ES,NE,E,ES
Q026_04714,BWHPSA013,NE,NE,NE,NE,NE,NE

In [16]:


accession_to_strain = {
    'GCA_000481765.1': '19660',
    'GCA_000480685.1': 'BL23',
    'GCA_000481605.1': 'BWHPSA005',
    'GCA_000481445.1': 'BWHPSA013',
    'GCA_000481405.1': 'BWHPSA015',
    'GCA_000480375.1': 'CF77',
    'GCA_000629365.1': 'PS75',
    'GCA_000014625.1': 'UCBPP-PA14',
    'GCA_000481705.1': 'X13273',
}

os.makedirs('05_pseudomonas/proteomes_renamed/', exist_ok=True)


metadata = []
for accession, strain in accession_to_strain.items():
    full_name = "Pseudomonas aeruginosa " + strain
    metadata.append({'full_name': full_name, 'accession': accession})
    
    ids_tested = set(list(suppl_table_03[suppl_table_03['Strain']==strain].index))
    
    infile = f"05_pseudomonas/proteomes/{accession}.gbff"
    sr_list = []
    ids_found = set()

    
    # use SeqIO.read() if you expect only one record in the GenBank file.
    # alternatively, use SeqIO.parse() if there are multiple records in the file.
    records = SeqIO.parse(infile, 'genbank')
    for record in records:

        # get scaffold information: 
        sequence_id = record.id
        sequence_description = record.description
        sequence_seqlen = len(record.seq)
        
        
        for feature in record.features:
            if feature.type == 'CDS':
                try: locus_tag = feature.qualifiers['locus_tag'][0]
                except: locus_tag = None
                try: aa_seq = feature.qualifiers['translation'][0]
                except: aa_seq = None
                
                if locus_tag not in ids_found:
                    sr = SeqRecord.SeqRecord(Seq.Seq(aa_seq), id=locus_tag, description='')
                    sr_list.append(sr)
                    ids_found.add(locus_tag)
                
    outfile = f'05_pseudomonas/proteomes_renamed/{strain}.faa'
    with open(outfile, 'w') as w_handler:
        count = SeqIO.write(sr_list, w_handler, "fasta")
        
        missing = ids_tested - ids_found
        print(f"Written '{outfile}'. Mentioned: {len(ids_tested)}. Added: {len(ids_found)}. Missing sequences: {len(missing)}.")
    
    
metadata = pnd.DataFrame.from_records(metadata)

Written '05_pseudomonas/proteomes_renamed/19660.faa'. Mentioned: 5891. Added: 6193. Missing sequences: 0.
Written '05_pseudomonas/proteomes_renamed/BL23.faa'. Mentioned: 6272. Added: 6606. Missing sequences: 0.
Written '05_pseudomonas/proteomes_renamed/BWHPSA005.faa'. Mentioned: 5956. Added: 6230. Missing sequences: 0.
Written '05_pseudomonas/proteomes_renamed/BWHPSA013.faa'. Mentioned: 5898. Added: 6113. Missing sequences: 0.
Written '05_pseudomonas/proteomes_renamed/BWHPSA015.faa'. Mentioned: 5622. Added: 5833. Missing sequences: 0.
Written '05_pseudomonas/proteomes_renamed/CF77.faa'. Mentioned: 6122. Added: 6402. Missing sequences: 0.
Written '05_pseudomonas/proteomes_renamed/PS75.faa'. Mentioned: 5558. Added: 5775. Missing sequences: 79.
Written '05_pseudomonas/proteomes_renamed/UCBPP-PA14.faa'. Mentioned: 5708. Added: 5892. Missing sequences: 1.
Written '05_pseudomonas/proteomes_renamed/X13273.faa'. Mentioned: 6261. Added: 6518. Missing sequences: 0.

In [17]:
os.makedirs('05_pseudomonas/tables/', exist_ok=True)
metadata[['full_name', 'accession']].to_excel('05_pseudomonas/tables/genomes.xlsx')
os.makedirs('06_pseudomonas/tables/', exist_ok=True)
metadata[['full_name', 'accession']].to_excel('06_pseudomonas/tables/genomes.xlsx')
metadata

                           full_name        accession
0       Pseudomonas aeruginosa 19660  GCA_000481765.1
1        Pseudomonas aeruginosa BL23  GCA_000480685.1
2   Pseudomonas aeruginosa BWHPSA005  GCA_000481605.1
3   Pseudomonas aeruginosa BWHPSA013  GCA_000481445.1
4   Pseudomonas aeruginosa BWHPSA015  GCA_000481405.1
5        Pseudomonas aeruginosa CF77  GCA_000480375.1
6        Pseudomonas aeruginosa PS75  GCA_000629365.1
7  Pseudomonas aeruginosa UCBPP-PA14  GCA_000014625.1
8      Pseudomonas aeruginosa X13273  GCA_000481705.1

# suppl table creation

In [25]:
df_concat = []
for dataset in ['01_klebsiella', '02_ralstonia', '03_pseudomonas', '04_streptococcus', '05_pseudomonas', '06_pseudomonas']:
    df = pnd.read_excel(f'{dataset}/tables/genomes.xlsx', index_col=0)
    if dataset == '05_pseudomonas': 
        df['accession'] = df['accession'] + ' (genbank annotation)'
        df['dataset'] = '05_pseudomonas, 06_pseudomonas'
    elif dataset == '06_pseudomonas': continue
    else: df['dataset'] = dataset
    df_concat.append(df)
df_concat = pnd.concat(df_concat).reset_index(drop=True)
df_concat.to_excel('tables/Supplementary Table 5.xlsx')
df_concat

,full_name,accession,dataset
0,Klebsiella africana 200023T,GCA_020526085.1,01_klebsiella
1,Klebsiella pneumoniae 03-9138-2,GCA_020526045.1,01_klebsiella
2,Klebsiella pneumoniae 04A025,GCA_020526025.1,01_klebsiella
3,Klebsiella pneumoniae BJ1,GCA_020526065.1,01_klebsiella
4,Klebsiella pneumoniae CG43,NC_022566.1 + NC_005249.1,01_klebsiella
...,...,...,...
105,Pseudomonas aeruginosa BWHPSA015,GCA_000481405.1 (genbank annotation),"05_pseudomonas, 06_pseudomonas"
106,Pseudomonas aeruginosa CF77,GCA_000480375.1 (genbank annotation),"05_pseudomonas, 06_pseudomonas"
107,Pseudomonas aeruginosa PS75,GCA_000629365.1 (genbank annotation),"05_pseudomonas, 06_pseudomonas"
108,Pseudomonas aeruginosa UCBPP-PA14,GCA_000014625.1 (genbank annotation),"05_pseudomonas, 06_pseudomonas"
109,Pseudomonas aeruginosa X13273,GCA_000481705.1 (genbank annotation),"05_pseudomonas, 06_pseudomonas"